SilphCo_4F_Text_CantYouSeeImHiding::
    .string "שש!\n"
    .string "אתה לא רואה שאני מתחבא?$"

SilphCo_4F_Text_TeamRocketIsGone::
    .string "מה?\n"
    .string "צוות רוקט הלכה?$"

SilphCo_4F_Text_Grunt1Intro::
    .string "צוות רוקט השתלטה\n"
    .string "על ארגון סילף!$"

SilphCo_4F_Text_Grunt1Defeat::
    .string "ארgh!$"

SilphCo_4F_Text_Grunt1PostBattle::
    .string "פוואהההה!\n"
    .string "הבוס שלי רודף אחרי המקום הזה!$"

SilphCo_4F_Text_RodneyIntro::
    .string "הפוקימון שלי הוא משרתי נאמן.$"

SilphCo_4F_Text_RodneyDefeat::
    .string "אסה!\n"
    .string "פוקימון חלש!$"

SilphCo_4F_Text_RodneyPostBattle::
    .string "הדלתות נעולות באופן אלקטרוני.\p"
    .string "צריך כרטיס גישה כדי לפתוח את\n"
    .string "הדלתות כאן.$"

SilphCo_4F_Text_Grunt2Intro::
    .string "זוהה פולש!$"

SilphCo_4F_Text_Grunt2Defeat::
    .string "מי אתה?$"

SilphCo_4F_Text_Grunt2PostBattle::
    .string "אני צריך לדווח לבוס בקומה 11!$"

SilphCo_4F_Text_FloorSign::
    .string "ארגון סילף. משרד ראשי\n"
    .string "קומה 4$"
