PokemonMansion_1F_Text_TedIntro::
    .string "מי אתה?\n"
    .string "לא אמור להיות כאן אף אחד.$"

PokemonMansion_1F_Text_TedDefeat::
    .string "אה!$"

PokemonMansion_1F_Text_TedPostBattle::
    .string "מפתח? אני לא יודע על מה\n"
    .string "אתה מדבר.$"

PokemonMansion_1F_Text_JohnsonIntro::
    .string "א-א-אה! הפחדת אותי!\n"
    .string "חשבתי שאתה רוח רפאים.$"

PokemonMansion_1F_Text_JohnsonDefeat::
    .string "טצ'!\n"
    .string "אני לא מצליח לנצח בכלל.$"

PokemonMansion_1F_Text_JohnsonPostBattle::
    .string "חקרתי כאן לבד,\n"
    .string "אבל אני מרגיש מפוחד.\p"
    .string "כדאי לי ללכת בקרוב.$"
