CeruleanCity_PokemonCenter_1F_Text_BillDoesWhateverForRareMons::
    .string "ביל הזה!\p"
    .string "שמעתי שהוא יעשה כל דבר כדי להשיג\l"
    .string "פוקימונים נדירים!$"

CeruleanCity_PokemonCenter_1F_Text_EveryoneCallsBillPokemaniac::
    .string "שמעת על ביל?\p"
    .string "כולם קוראים לו פוקימטורף!\p"
    .string "אבל אני חושב שאנשים סתם\l"
    .string "מקנאים בביל.\p"
    .string "מי לא היה רוצה להשוויץ\l"
    .string "בפוקימונים שלהם?$"

CeruleanCity_PokemonCenter_1F_Text_BillCollectsRareMons::
    .string "לביל יש מלא פוקימונים!\n"
    .string "הוא אוסף פוקימונים נדירים!$"

CeruleanCity_PokemonCenter_1F_Text_TryTradingUpstairs::
    .string "למה שלא תעלה לקומה למעלה ותנסה\n"
    .string "להחליף פוקימונים עם חברים?\p"
    .string "הפוקימונים שאתה מקבל בהחלפות\n"
    .string "גם גדלים מהר.$"

