CeladonCity_Condominiums_RoofRoom_Text_TheresNothingIDontKnow::
    .string "There is nothing that I don't know,\n"
    .string "like I wrote on the blackboard.\p"
    .string "I know about the world of POKéMON\n"
    .string "in your GAME BOY ADVANCE!\p"
    .string "Get together with your friends and\n"
    .string "enjoy trading POKéMON!$"

CeladonCity_Condominiums_RoofRoom_Text_ObtainedAnEevee::
    .string "{PLAYER} קיבל איווי!$"

CeladonCity_Condominiums_RoofRoom_Text_BoxIsFull::
    .string "ポケモンが　いっぱいだ\n"
    .string "ボックスを　かえて　きなさい$"

CeladonCity_Condominiums_RoofRoom_Text_WirelessAdapterLecture::
    .string "הרצאות פוקימון\p"
    .string "לשחק עם מתאם על-חוטי$"

CeladonCity_Condominiums_RoofRoom_Text_ReadWhichHeading::
    .string "איזה נושא תרצה לקרוא?$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainWirelessClub::
    .string "מועדון הפוקימון העל חוטי נמצא\n"
    .string "בקומה העליונה בכל מרכז פוקימונים.\p"
    .string "בקר שם כדי להתחבר עם חברים שלך\n"
    .string "באמצעות התאם על-חוטי.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainDirectCorner::
    .string "כדי להתחבר עם חבר בלבד\n"
    .string "לך לפינה הישירה.\p"
    .string "זה הדלפק הימני\n"
    .string "במועדון הפוקימון העל חוטי.\p"
    .string "היכנס לפינת ההחלפות או\n"
    .string "ל-קולוסאום עם חבריך.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainUnionRoom::
    .string "כדי להתחבר ולתקשר עם כל אחד,\n"
    .string "לך לחדר החיבור.\p"
    .string "זה הדלפק השמאלי\n"
    .string "במועדון הפוקימון העל חוטי.\p"
    .string "לך לחדר החיבור ותפגוש\n"
    .string "מאמנים אחרים.$"

CeladonCity_Condominiums_RoofRoom_Text_PamphletOnTMs::
    .string "זה עלון על מ”מ.\p"
    .string "… …\p"
    .string "יש בסך הכל 50 מ”מ.\p"
    .string "יש גם 7 מ”נ\n"
    .string "שאפשר להשתמש בהם הרבה פעמים.\p"
    .string "חברת סילף.$"

