PokemonMansion_B1F_Text_LewisIntro::
    .string "אוי-אוי…\n"
    .string "איפה אני עכשיו?$"

PokemonMansion_B1F_Text_LewisDefeat::
    .string "אווו!$"

PokemonMansion_B1F_Text_LewisPostBattle::
    .string "אפשר למצוא דברים מונחים מסביב.\n"
    .string "הדיירים בטח השאירו אותם.$"

PokemonMansion_B1F_Text_IvanIntro::
    .string "המקום הזה אידיאלי למעבדה.\n"
    .string "תראה את כל המקום הזה.$"

PokemonMansion_B1F_Text_IvanDefeat::
    .string "בשביל מה זה היה?$"

PokemonMansion_B1F_Text_IvanPostBattle::
    .string "אני אוהב את זה כאן.\n"
    .string "זה תורם ללימודים שלי.$"

PokemonMansion_B1F_Text_MewtwoIsFarTooPowerful::
    .string "יומן: 1 בספטמבר\n"
    .string "מיוטו חזק מדי.\p"
    .string "נכשלנו לרסן את הנטיות\n"
    .string "האכזריות שלו…$"
