FuchsiaCity_House1_Text_WardenIsOldHasFalseTeeth::
    .string "הפקח של אזור\n"
    .string "הספארי כבר מבוגר, אבל הוא עדיין\l"
    .string "פעיל!\p"
    .string "מה שכן, כל השיניים שלו הן תותבות.$"

FuchsiaCity_House1_Text_BillIsMyGrandson::
    .string "מה אתה אומר?\n"
    .string "פגשת את ביל?\p"
    .string "הוא הנכד שלי!\p"
    .string "אפילו בתור ילד הוא תמיד אהב\l"
    .string "לאסוף דברים!$"

FuchsiaCity_House1_Text_BillFilesHisOwnMonData::
    .string "ביל מתייק את\n"
    .string "פרטי הפוקימונים שלו במחשב!\p"
    .string "אם תבקש ממנו, אולי\n"
    .string "הוא יראה לך איך!$"
