Route7_EastEntrance_Text_ThirstyOnGuardDuty::
    .string "אני בתורנות שמירה.\n"
    .string "אוי, אני צמא, אבל!\p"
    .string "אה, חכה שם, הדרך סגורה.$"

Route7_EastEntrance_Text_ThatTeaLooksTasty::
    .string "אה, התה הזה…\n"
    .string "נראה טעים מאוד…$"

Route7_EastEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "מה? אני יכול לקבל את המשקה הזה?\n"
    .string "אוי, תודה!\l"
    .string "… …\l"
    .string "גלוג, גלוג…\l"
    .string "… …\l"
    .string "גולפ…\l"
    .string "אם אתה רוצה ללכת לסאפרון\l"
    .string "סיטי…\l"
    .string "… …\l"
    .string "תוכל לעבור.\p"
    .string "אני אשתף את התה הזה עם שאר\n"
    .string "השומרים!$"

Route7_EastEntrance_Text_HiHowsItGoing::
    .string "היי, מה המצב?$"
