SaffronCity_CopycatsHouse_1F_Text_DaughterIsSelfCentered::
    .string "הבת שלי כל כך מרוכזת בעצמה.\n"
    .string "יש לה רק כמה חברים.$"

SaffronCity_CopycatsHouse_1F_Text_DaughterLikesToMimicPeople::
    .string "הבת שלי אוהבת לחקות אנשים.\n"
    .string "זה די מטריד.\p"
    .string "החיקויים שלה זיכו אותה\n"
    .string "בכינוי 'חקיינית' בסביבה.$"

SaffronCity_CopycatsHouse_1F_Text_Chansey::
    .string "צ'נסי: צ'אן! סי!$"
