PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround::
    .string "{RIVAL}: NJ,\n"
    .string "{PLAYER}! SFEP'I PE OEa!$"

PalletTown_ProfessorOaksLab_Text_RivalFedUpWithWaiting::
    .string "{RIVAL}: SFEP'I!\n"
    .string "RJ, RQES PN OFX PLOJZ!$"

PalletTown_ProfessorOaksLab_Text_RivalNoFairWhatAboutMe::
    .string "{RIVAL}: INN!\n"
    .string "SFEP'I! QI ENZN?$"

PalletTown_ProfessorOaksLab_Text_RivalGoChoosePlayer::
    .string "{RIVAL}: LI,\n"
    .string "ERN PE LQHa OQJe! RJ, ZFLX OFX,\n"
    .string "{PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_RivalIllTakeThisOneThen::
    .string "{RIVAL}: EK ERN\n"
    .string "EWL EZ IELH IKI!$"

PalletTown_ProfessorOaksLab_Text_RivalReceivedMonFromOak::
    .string "{RIVAL} WNFP\n"
    .string "{} !{}$"

PalletTown_ProfessorOaksLab_Text_RivalMyMonLooksTougher::
    .string "{RIVAL}: IUJWNQJa\n"
    .string "YPN RXEI IXFI NJZX LKW.$"

PalletTown_ProfessorOaksLab_Text_RivalLetsCheckOutMons::
    .string "{RIVAL}: LOI\n"
    .string "XGT, {PLAYER}! FJE RRSI WVZ\l"
    .string "EZ IUJWNQJRNb ILHYNb YPRJ!\p"
    .string "WHNQI, ERN QEZGX EJZe PWXF!$"

PalletTown_ProfessorOaksLab_Text_RivalDefeat::
    .string "QI???\n"
    .string "ERN PE QEQNa! FLXZN EZ IUJWNQJa\l"
    .string "IPE ROJa!\p$"

Text_RivalVictory::
    .string "{RIVAL}: Oa! ERN\n"
    .string "QHINb EJ QI?\p$"

PalletTown_ProfessorOaksLab_Text_RivalGoToughenMyMon::
    .string "{RIVAL}: FSHX!\n"
    .string "ERN IJPe PGXJb PUJWNQJa YPN\l"
    .string "PINPLb OHN YNINI WVZ NJZX WYJL!\p"
    .string "{PLAYER}! SFEP'I! RZXLXL ELX-Oe!$"

PalletTown_ProfessorOaksLab_Text_RivalGramps::
    .string "{RIVAL}: SFEP'I!$"

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor::
    .string "{RIVAL}: PQI WXEZ\n"
    .string "PN?$"

PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps::
    .string "{RIVAL}: ENa FTNI,\n"
    .string "SFEP'I! ZYENX EZ KI PN!$"

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap::
    .string "{PLAYER}, PE RTNb\n"
    .string "PN PJQX, EFP ERN\l"
    .string "PE VXNe EZ TKXZe!\p"
    .string "NY PN XTNJa! ERN EFWY QELJZN\l"
    .string "PYEJP QQRI QUI!\p"
    .string "ERN EJQX PI YPE ZYENP Pe QUI,\l"
    .string "{PLAYER}! LI LI!$"

PalletTown_ProfessorOaksLab_Text_OakThreeMonsChooseOne::
    .string "EJW: {RIVAL}?\n"
    .string "Za PN PINKOX...\p"
    .string "EI, ROJa, WXEZN Pe POEa! LOI XGT!\p"
    .string "IRI, {PLAYER}!\p"
    .string "NY 3 UJWNQJRNb TP IYJPLa!\p"
    .string "ENUI? LI LI!\p"
    .string "Ib FZJe IUJWNFJPNb.\p"
    .string "INNZN QEQa UJWNQJa XVNRN FKQRN!\p"
    .string "TOYNJ OYERN QFJGX, RYEXJ PN XW 3,\l"
    .string "EFP EZI NOJP PWLZ ELH! FLX!$"

PalletTown_ProfessorOaksLab_Text_OakBePatientRival::
    .string "EJW: SFPRJZ,\n"
    .string "{RIVAL}! Gb EZI ZWFP ELH!$"

PalletTown_ProfessorOaksLab_Text_OakWhichOneWillYouChoose::
    .string "EJW: {PLAYER},\n"
    .string "FZJe YPJYZ IUJWNFJPNb IEPJ\n"
    .string "NYRb UJWNQJRNb."
    .string "ENKI QIb ZFLX PTVQe?$"

PalletTown_ProfessorOaksLab_Text_OakHeyDontGoAwayYet::
    .string "EJW: INN! THNNa\n"
    .string "PE FLXZ!$"

PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander::
    .string "EK EZI XJVI EZ\n"
    .string "UJWNQJa IEY, V'XQRHX?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle::
    .string "EK EZI XJVI EZ\n"
    .string "UJWNQJa IQNb, SWJJNXMP?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur::
    .string "EK EZI XJVI EZ\n"
    .string "UJWNQJa IHYE, FPFEKJX?$"

PalletTown_ProfessorOaksLab_Text_OakThisMonIsEnergetic::
    .string "KI UJWNQJa\n"
    .string "QPE QXc!\p$"

PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak::
    .string "{PLAYER} WNFP\n"
    .string "{} !{}$"

PalletTown_ProfessorOaksLab_Text_OakCanReachNextTownWithMon::
    .string "EJW: Eb QJUNT UJWNQJa FX,\n"
    .string "EZI NOJP PINPLb FJ.\p"
    .string "Tb IUJWNQJa PVNHe EZI NOJP\n"
    .string "PIGNT PTNX IFEI FFMLI.$"

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow::
    .string "EJW: {PLAYER},\n"
    .string "ZEQa EZ IUJWNQJa\l"
    .string "IVTNX YPe FWXFJZ!$"

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe::
    .string "EJW: EI, {PLAYER}!\p"
    .string "QI YPJb IUJWNQJa YRZZN Pe?\p"
    .string "MJF, RXEI YIJE EJIF EJZe QEJH.\p"
    .string "ORXEI YEZI QEQa UJWNQJRNb QJOYX!\p"
    .string "QI? IFEZ PN QYIJ?$"

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel::
    .string "{PLAYER} QSX\n"
    .string "EZ ILFNPI YP EJW.$"

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered::
    .string "EI! KI IUJWNFJP\n"
    .string "IQNJLH YIKQRZN! ZJHI Pe!$"

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo::
    .string "EJW: NY PN FWYI\n"
    .string "TFJX YRNOb.$"

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk::
    .string "TP IYJPLa RQVEZ\n"
    .string "IIQVEI ILHYI YPN, IUJWHWS!\p"
    .string "IUJWHWS QZTH QNHT PGFN UJWNQJRNb\l"
    .string "YZUSZb EJ XENZb! IJE EJMJQMN\l"
    .string "PLPJMNa!\p"
    .string "KI OQJ ERVNWPJUHNI QZWHQZ!$"

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou::
    .string "EJW: {PLAYER}\n"
    .string "J{RIVAL}! WLJ POb ELH!$"

PalletTown_ProfessorOaksLab_Text_ReceivedPokedexFromOak::
    .string "{PLAYER} WNFP\n"
    .string "QEJW EZ IUJWHWS!{}$"

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese::
    .string "EJW: Eb EZI XJVI\n"
    .string "PHTZ UXMNb QHJNWNb TP\l"
    .string "UJWNQJa, TPNe PTYJZ NJZX QXW\l"
    .string "PXEJZ EJZJ.\p"
    .string "TPNe PZUJS EJZJ! IYZQY FEPI OHN\l"
    .string "PZUJS UJWNQJRNb UXENNb.$"

PalletTown_ProfessorOaksLab_Text_ReceivedFivePokeBalls::
    .string "{PLAYER} WNFP 5\n"
    .string "UJWNFJPNb!{}$"

PalletTown_ProfessorOaksLab_Text_OakExplainCatching::
    .string "OYUJWNQJRNb UXEN\n"
    .string "QJUNT, IJE RLPZ IOPP.\p"
    .string "OP QI YVXNe IJE\n"
    .string "PKXJW TPNJ UJWNFJP JPRSJZ PZUJS\l"
    .string "EJZJ!\p"
    .string "PE ZQNH ZVPNL PZUJS EZ IUJWNQJa.\p"
    .string "UJWNQJa FXNE NOJP PINQPM QIOHJX.\l"
    .string "VXNe PWJJZ PQKP!$"

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream::
    .string "ILPJb YPN ZQNH\n"
    .string "INI...\p"
    .string "POZJF QHXNe QUJXM TP OP SJGN\l"
    .string "IUJWNQJa YNY!\p"
    .string "EFP ERN OFX PE VTNX OQJ YINNZN.\l"
    .string "KI OFX PE FYFNPN.\p"
    .string "EK ERN XJVI YEZb ZGYNQJ EZ ILPJb\l"
    .string "YPN!\p"
    .string "WHNQI, VEJ PHXe!\p"
    .string "KI XGT QYQTJZN FINSMJXNI YP\l"
    .string "UJWNQJa!$"

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait::
    .string "UJWNQJRNb FOP\n"
    .string "ITJPb QQZNRNb Pe, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex::
    .string "INN, {PLAYER}!\n"
    .string "ENe QZWHb Pe Tb IUJWNHWS?\p"
    .string "{RIVAL} OFX ZUS OQI UJWNQJRNb JIJSNd\n"
    .string "QNHT TPNIb.\p"
    .string "EK {PLAYER} FJE RTNd QFM TP\n"
    .string "IUJWNHWS YPe.\p"
    .string "QI WXI?\n"
    .string "PE IJSUZ YJb QNHT PUJWNHWS.\p"
    .string "ERN EZa Pe EZ EPJ,\n"
    .string "EK ZYZHP WVZ NJZX.$"

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime::
    .string "EJW: FJE PFWX\n"
    .string "QHN UTb.\p"
    .string "EYQL PXEJZ EZ IIZWHQJZ YPe\l"
    .string "FIYPQZ IUJWHWS.$"

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia::
    .string "KI RXEI OQJ\n"
    .string "ERVNWPJUHNI, EFP OP IHUNb XNWNb!$"

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls::
    .string "KI UJWNFJP.\n"
    .string "NY FZJOJ UJWNQJa!$"

PalletTown_ProfessorOaksLab_Text_OaksLastMon::
    .string "KI IUJWNQJa IELXJa\n"
    .string "YP UXJU' EJW!$"

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu::
    .string "PLc TP OUZJX IIZLP OHN PUZJL\n"
    .string "EZ IZUXNM$"

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu::
    .string "HXe IZUXNM EUYX PYQJX EZ IQYLW.$"

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints::
    .string "POP SJGN IUJWNQJRNb NY NZXJRJZ\n"
    .string "JLJPYJZ QJP SJGNb ELXNb$"

PalletTown_ProfessorOaksLab_Text_EmailMessage::
    .string "NY UI IJHTZ QNNP.\p"
    .string "...\p"
    .string "SJd SJd! IQEQRNb ILKWNb FNJZX YP\l"
    .string "PNGZ IUJWNQJRNb QJORNb\l"
    .string "PINPLb FQN YXJVI PZUJS EZ QWJQb!\p"
    .string "QXOK PNGZ IUJWNQJRNb\n"
    .string "ENRHNGJ UPEMJ\p"
    .string "UXJUSJX EJW, FFWYI ZFWX EJZRJ Yb!\n"
    .string "...$"

PalletTown_ProfessorOaksLab_Text_StudyAsOaksAide::
    .string "ERN ITJKX YP\n"
    .string "UXJU' EJW. ERN LJWX UJWNQJRNb.$"

PalletTown_ProfessorOaksLab_Text_DaisyWillGroomMons::
    .string "INN {PLAYER}. ERN FMJL YEZI JIUJWNQJRNb\n"
    .string "YPe OFX RINNZb LFXNb MJFNb.\p"
    .string "HXe EGF, EZI NJHT PGFN HNNKN?\p"
    .string "Eb ZXEI PHNNKN EZ IUJWNQJa YPe\n"
    .string "INE ZHT PIGNH Pe OQI IJE EJIF EJZe.\p"
    .string "PUTQNb INE EUNPJ ZMUP FJ FYFNPe.\p"
    .string "KI SJH, FFWYI EP ZSUX EZ KI PEd ELH.$"

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow::
    .string "UXJU' EJW IJE\n"
    .string "I-QJQLI FOP QI YRJGT PUJWNQJa!\p"
    .string "QEQRN UJWNQJa XFNb XJLYNb OPUNJ\l"
    .string "OFJH XF!$"

PalletTown_ProfessorOaksLab_Text_OakIsAuthorityOnMons::
    .string "PELXJRI RVUJ UJWNQJRNb\n"
    .string "QIQJa KRNb RHNXNb.\p"
    .string "ERN QHFX TP UJWNQJRNb\n"
    .string "YQTJPb PE RXEJ UI FWERMJ.\p"
    .string "INNZN YQL PPOZ PXEJZ EJZb FTVQN,\n"
    .string "EFP ERN OFX KWa QNHN.\p"
    .string "QONJJa YERN PE NOJP PTYJZ EZ KI,\n"
    .string "{PLAYER}, ERN EYQL YZTYI KEZ FYFNPN.$"

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer::
    .string "{RIVAL}: INN! YQTZN EZ KI!\p"
    .string "SFE QI RSGX Tb KI YEZI\n"
    .string "QTHNd EZ {PLAYER} TP URN?\p"
    .string "ERN OFX IPOZN JZUSZN QPE UJWNQJRNb,\n"
    .string "JTYNZN EZ KI QIX.\p"
    .string "EZI NOJP PZZ PN PMUP FIOP,\n"
    .string "PE VXNe EZ {PLAYER}.$"

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons::
    .string "EJW: ERN NJHT, ERN NJHT\n"
    .string "OQJFa YERN VXNe Gb EZ TKXZe.\p"
    .string "YRNOb, ZFNEJ PN EZ IUJWHWSNb YPOb.$"

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything::
    .string "UXJU EJW PWL EZ YRN IUJWHWSNb.$"

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes::
    .string "… … …  … … …\p"
    .string "… … …  … … …\p"
    .string "J... KIJ!\p"
    .string "TOYNJ Ib NJOPJ PIWPNM QNHT\n"
    .string "TP TJH IQJa UJWNQJRNb.$"

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits::
    .string "IUJWHWS YP {PLAYER} YJHXG!$"

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData::
    .string "TOYNJ, {PLAYER} J{RIVAL}!\p"
    .string "EZb QQY LNNFNb PQPE EZ\n"
    .string "IUJWHWSNb YPOb.\p"
    .string "ERN SJQe TPNOb YZIUOJ EJZb\n"
    .string "PION QPENb JMJFNb FOP ITJPb!\p"
    .string "IXGT IKI NKOX OXGT LYJF QEJH\n"
    .string "FINSMJXNI YP QHT IUJWNQJRNb!$"

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded::
    .string "{RIVAL}: SFE, EP ZZXGY NJZX QNHN.\p"
    .string "ERN EQPE EZ IUJWHWS YPN,\n"
    .string "ENa Pe SNFI PHEJG.\p"
    .string "ERN LJYF YEZLNP F-EN QSUX 1.\p"
    .string "FOP QWXI ERN IJPe!$"

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex::
    .string "PUXJUSJX EJW IJPOZ PINJZ ZJORNZ XHNJ\n"
    .string "FWXJF\p"
    .string "INE IJPOZ PINWXE SQNRX IUJWNQJRNb$"

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex::
    .string "EJ KI QVJNa!\p"
    .string "{PLAYER} NY PN TJH FWYI LYJFI TFJXe.\n"
    .string "ERN VXNe YZWYNF PN MJF.$"