CeladonCity_DepartmentStore_2F_Text_SuperRepelMorePowerfulRepel::
    .string "דוחה על ירחיק\n"
    .string "ממך פוקימונים חלשים...\p"
    .string "הממ, זה כמו דוחה חזק במיוחד!$"

CeladonCity_DepartmentStore_2F_Text_BuyReviveForLongOutings::
    .string "כדאי להצטייד\n"
    .string "בהחייאה אם אתה יוצא למסע ארוך.$"

CeladonCity_DepartmentStore_2F_Text_FloorSign::
    .string "פריטים איכותיים\n"
    .string "שמאמנים אוהבים!\p"
    .string "ק2: הכל למאמן$"

CeladonCity_DepartmentStore_2F_Text_LanceComesToBuyCapes::
    .string "יש לנו לקוח ששמו לראנס שמגיע\n"
    .string "מידי פעם.\p"
    .string "הוא תמיד קונה גלימות.\p"
    .string "אני תוהה… האם יש לו המון\n"
    .string "גלימות זהות בבית?$"
