VermilionCity_House3_Text_PidgeyFlyLetterToSaffron::
    .string "אני שולח את פידג'י שלי להעיף\n"
    .string "מכתב לסאפרון שבצפון.$"

VermilionCity_House3_Text_Pidgey::
    .string "פידג'י: קורוקקו!$"

VermilionCity_House3_Text_DearPippiLetter::
    .string "פיפי היקרה,\n"
    .string "מקווה לראותך בקרוב.\p"
    .string "שמעתי שלסאפרון יש בעיות עם\n"
    .string "צוות רוקט.\p"
    .string "נראה כי ורמיליון בטוחה.$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom::
    .string "אני רוצה להחליף דואר עם כל מיני\n"
    .string "אנשים.\p"
    .string "אני שולח את פידג'י שלי לחדר\n"
    .string "האיחוד כדי להחליף דואר בשבילי.$"
