VictoryRoad_1F_Text_NaomiIntro::
    .string "אני תוהה אם אתה טוב מספיק\n"
    .string "בשבילי?$"

VictoryRoad_1F_Text_NaomiDefeat::
    .string "הפסדתי…$"

VictoryRoad_1F_Text_NaomiPostBattle::
    .string "מעולם לא רציתי להפסיד למישהו,\n"
    .string "בטח שלא לילד צעיר ממני…$"

VictoryRoad_1F_Text_RolandoIntro::
    .string "אני רואה שאתה טוב.\n"
    .string "תן לי לראות בדיוק כמה טוב!$"

VictoryRoad_1F_Text_RolandoDefeat::
    .string "היה לי סיכוי…$"

VictoryRoad_1F_Text_RolandoPostBattle::
    .string "צ'ח!\n"
    .string "אני מוותר, אתה טוב ממני!$"
