Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
    .string "פוקימונים רבים חיים רק ביערות\n"
    .string "ובמערות.\p"
    .string "עליך להיות עקשן ולחפש בכל מקום\n"
    .string "כדי למצוא סוגים שונים.$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
    .string "האם שמת לב לעצים הדקים\n"
    .string "בצדי הדרך?\p"
    .string "שמעתי שהם ניתנים לחיתוך על ידי\n"
    .string "תנועת פוקימון מיוחדת.$"

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
    .string "האם אתה מכיר את טכניקת ביטול\n"
    .string "האבולוציה?\p"
    .string "כשפוקימון מתפתח, אתה יכול לעצור\n"
    .string "את התהליך.\p"
    .string "זו טכניקה לגידול פוקימונים כפי\n"
    .string "שהם.$"
