SSAnne_Kitchen_Text_BusyOutOfTheWay::
    .string "אתה, מון פטי!\n"
    .string "אנחנו עסוקים כאן!\l"
    .string "צא מהדרך!$"

SSAnne_Kitchen_Text_SawOddBerryInTrash::
    .string "ראיתי פרי מוזר בפח.\n"
    .string "אני תוהה מה זה היה?$"

SSAnne_Kitchen_Text_SoBusyImDizzy::
    .string "אני כל כך עסוק שאני מסתחרר!\n"
    .string "אתה חייב לתת לי מקום כאן!$"

SSAnne_Kitchen_Text_PeelSpudsEveryDay::
    .string "האם-דה-האם-דה-הו…\p"
    .string "אני מקלף תפוחי אדמה כל יום!\n"
    .string "האם-האם…$"

SSAnne_Kitchen_Text_HearAboutSnorlaxItsAGlutton::
    .string "שמעת על סנורלקס?\n"
    .string "הוא זללן.\p"
    .string "אין פוקימון אחר שאוכל וישן\n"
    .string "כמו שסנורלקס יכול ועושה!$"

SSAnne_Kitchen_Text_OnlyGetToPeelOnions::
    .string "התייפחות… הרחה…\p"
    .string "אני רק מקבל לקלף בצלים…\n"
    .string "התייפחות…$"

SSAnne_Kitchen_Text_IAmLeChefMainCourseIs::
    .string "אה-הם!\n"
    .string "אכן אני השף!\p"
    .string "המנה העיקרית היא$"

SSAnne_Kitchen_Text_SalmonDuSalad::
    .string "סלמון בסלט!\p"
    .string "האורחים עלולים להתלונן שזה\n"
    .string "דג שוב, בכל אופן!$"

SSAnne_Kitchen_Text_EelsAuBarbecue::
    .string "צלופחים על הגריל!\p"
    .string "אני חושש שהאורחים יתמרדו.$"

SSAnne_Kitchen_Text_PrimeBeefsteak::
    .string "סטייק פריים!\p"
    .string "אבל, האם יש לי מספיק פילטים\n"
    .string "של בקר?$"
