FuchsiaCity_Gym_Text_KogaPostBattle::
    .string "תחת השפעת המהלך\n"
    .string "הרעלה, פוקימון יסבול מהרעל יותר\l"
    .string "ויותר ככל שהקרב יתקדם!\p"
    .string "אויביך ירעדו מפחד!$"

FuchsiaCity_Gym_Text_KogaExplainSoulBadge::
    .string "בזכות תג הלב,\n"
    .string "נתוני ההגנה של הפוקימונים שלך\l"
    .string "הוגברו!\p"
    .string "התג גם מאפשר לך להשתמש בגלישה\l"
    .string "מחוץ לקרב!\p"
    .string "אה! קח גם את זה!$"

FuchsiaCity_Gym_Text_ReceivedTM06FromKoga::
    .string "{PLAYER} קיבל את מ"מ06$"

FuchsiaCity_Gym_Text_KogaExplainTM06::
    .string "מ”מ06 מכיל את\n"
    .string "המהלך הרעלה!\p"
    .string "זה מהלך סודי בן יותר מ-400 שנים!$"

FuchsiaCity_Gym_Text_MakeSpaceForThis::
    .string "פנה מקום בתיק,\n"
    .string "ילד!$"

FuchsiaCity_Gym_Text_KaydenIntro::
    .string "כוח הוא לא המפתח\n"
    .string "לניצחון בקרבות פוקימון!\p"
    .string "המפתח האמיתי הוא אסטרטגיה!\p"
    .string "אני אראה לך איך אסטרטגיה מסוגלת\l"
    .string "בלייןיס גישה כוחנית!$"

FuchsiaCity_Gym_Text_KaydenDefeat::
    .string "מה?\n"
    .string "יוצא מן הכלל!\p$"

FuchsiaCity_Gym_Text_KaydenPostBattle::
    .string "אז אתה משתמש\n"
    .string "בשילוב בין כוח למוח? אסטרטגיה\l"
    .string "טובה!$"

FuchsiaCity_Gym_Text_KirkIntro::
    .string "רציתי ללמוד להיות\n"
    .string "נינג'ה, אז הצטרפתי למכון הזה!$"

FuchsiaCity_Gym_Text_KirkDefeat::
    .string "הלך\n"
    .string "עליי!\p$"

FuchsiaCity_Gym_Text_KirkPostBattle::
    .string "אני אמשיך להתאמן\n"
    .string "בבילכתו של קוגה, מאסטר הנינג'ה\l"
    .string "שלי!$"

FuchsiaCity_Gym_Text_NateIntro::
    .string "בוא נראה אותך\n"
    .string "מנצח את הטכניקות המיוחדות שלי!$"

FuchsiaCity_Gym_Text_NateDefeat::
    .string "הטעית\n"
    .string "אותי!\p$"

FuchsiaCity_Gym_Text_NatePostBattle::
    .string "אני אוהב מהלכים\n"
    .string "שגורמים לשינה ולהרעלה, כי\l"
    .string "ההשפעה שלהם נמשכת גם אחרי הקרב!$"

FuchsiaCity_Gym_Text_PhilIntro::
    .string "עברוק!\p"
    .string "הקירות הבלתי- נראים שלנו\l"
    .string "מתסכלים אותך?$"

FuchsiaCity_Gym_Text_PhilDefeat::
    .string "וואו!\n"
    .string "הוא קלט את זה!\p$"

FuchsiaCity_Gym_Text_PhilPostBattle::
    .string "אני ממש מתרשם!\n"
    .string "קח רמז!\p"
    .string "חפש את המעברים שבין הקירות הבלתי\l"
    .string "-נראים!$"

FuchsiaCity_Gym_Text_EdgarIntro::
    .string "גם אני לומד את\n"
    .string "סודות הנינג'ה ממאסטר קוגה!\p"
    .string "לנינג'ות יש מסורת של שימוש בחיות!$"

FuchsiaCity_Gym_Text_EdgarDefeat::
    .string "אעוו!\p$"

FuchsiaCity_Gym_Text_EdgarPostBattle::
    .string "עדיין יש לי הרבה\n"
    .string "מה ללמוד!$"

FuchsiaCity_Gym_Text_ShawnIntro::
    .string "מאסטר קוגה מגיע\n"
    .string "לשושלת ארוכה של נינג'ות!\p"
    .string "מאיזו שושלת אתה מגיע?$"

FuchsiaCity_Gym_Text_ShawnDefeat::
    .string "הפלתי\n"
    .string "את הכדורים שלי!"

FuchsiaCity_Gym_Text_ShawnPostBattle::
    .string "איפה שיש אור, יש\n"
    .string "גם חושך!\p"
    .string "אור וחושך! באיזה צד תבחר?$"

FuchsiaCity_Gym_Text_GymGuyAdvice::
    .string "יו!\n"
    .string "אלופצ'יק!\p"
    .string "מכון פיושה מלא בקירות בלתי-\l"
    .string "נראים!\p"
    .string "אולי זה נראה שקוגה קרוב, אבל הדרך\l"
    .string "אליו חסומה!\p"
    .string "תצטרך למצוא רווחים בין הקירות כדי\l"
    .string "להגיע אליו!$"

FuchsiaCity_Gym_Text_GymGuyPostVictory::
    .string "זה מדהים, לנינג'ות\n"
    .string "יש כוח הרתעה, אפילו בימינו!$"

FuchsiaCity_Gym_Text_GymStatue::
    .string "מכון הפוקימונים פיושה\n"
    .string "מנהיג: קוגה\p"
    .string "מאמנים שניצחו:\n"
    .string "{RIVAL}$"

FuchsiaCity_Gym_Text_GymStatuePlayerWon::
    .string "מכון הפוקימונים פיושה\n"
    .string "מנהיג: קוגה\p"
    .string "מאמנים שניצחו:\n"
    .string "{RIVAL}, {PLAYER}$"