VermilionCity_House1_Text_ImFishingGuruDoYouLikeToFish::
    .string "אני גורו הדיג!\p"
    .string "אני פשוט אוהב לדוג!\n"
    .string "אני לא יכול בלעדיו.\p"
    .string "תגיד לי, אתה אוהב לדוג?$"

VermilionCity_House1_Text_TakeThisAndFish::
    .string "נפלא! אני אוהב את הסגנון שלך.\n"
    .string "אני חושב שנוכל להיות חברים.\p"
    .string "קח את זה וצא לדוג, חבר צעיר!$"

VermilionCity_House1_Text_ReceivedOldRodFromFishingGuru::
    .string "{PLAYER} קיבל חכה ישנה\n"
    .string "מגורו הדיג.$"

VermilionCity_House1_Text_FishingIsAWayOfLife::
    .string "דיג הוא דרך חיים!\n"
    .string "זה כמו שירה במיטבה.\p"
    .string "מהימים לנהרות, צא ותפוס\n"
    .string "את הגדול, חברי.$"

VermilionCity_House1_Text_OhThatsSoDisappointing::
    .string "אוי...\n"
    .string "זה כל כך מאכזב...$"

VermilionCity_House1_Text_HowAreTheFishBiting::
    .string "שלום לך, {PLAYER}!\p"
    .string "איך הולך הדיג?$"

VermilionCity_House1_Text_NoRoomForNiceGift::
    .string "אוי, לא!\p"
    .string "היה לי מתנה יפה בשבילך, אבל אין\n"
    .string "לך מקום בשבילה!$"
