SSAnne_1F_Room6_Text_TakeAShortRest::
    .string "אתה נראה עייף. האם תרצה\n"
    .string "לנוח קצת?$"

SSAnne_1F_Room6_Text_GladEveryoneIsRefreshed::
    .string "אני שמח לראות שכולם נראים\n"
    .string "רעננים ומלאי מרץ.$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMyBrother::
    .string "אה, סליחה שהתעסקתי איתך.\n"
    .string "אתה נראה כמו אחי הקטן…$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMySister::
    .string "אה, סליחה שהתעסקתי איתך.\n"
    .string "אתה נראה כמו אחותי הקטנה…$"
