PokemonLeague_BrunosRoom_Text_Intro::
    .string "אני ברונו מהרביעייה העילית!\p"
    .string "דרך אימונים קפדניים, אנשים\n"
    .string "ופוקימונים יכולים להתחזק\l"
    .string "ללא גבול.\p"
    .string "חייתי ואימנתי עם\n"
    .string "פוקימוני הלחימה שלי!\l"
    .string "וזה לעולם לא ישתנה!\p"
    .string "{PLAYER}!\p"
    .string "נשחק אותך עם הכוח\n"
    .string "העליון שלנו!\p"
    .string "הו הא!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_BrunosRoom_Text_RematchIntro::
    .string "אני ברונו מהרביעייה העילית!\p"
    .string "דרך אימונים קפדניים, אנשים\n"
    .string "ופוקימונים יכולים להתחזק\l"
    .string "ללא גבול.\p"
    .string "חייתי ואימנתי עם\n"
    .string "פוקימוני הלחימה שלי!\l"
    .string "וזה לעולם לא ישתנה!\p"
    .string "{PLAYER}!\p"
    .string "נשחק אותך עם הכוח\n"
    .string "העליון שלנו!\p"
    .string "הו הא!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_BrunosRoom_Text_Defeat::
    .string "למה?\n"
    .string "איך יכולתי להפסיד?$"

PokemonLeague_BrunosRoom_Text_PostBattle::
    .string "התפקיד שלי הסתיים.\n"
    .string "לך להתמודד עם האתגר הבא.$"
