SilphCo_8F_Text_WonderIfSilphIsFinished::
    .string "אני תוהה אם ארגון סילף גמור…$"

SilphCo_8F_Text_ThanksForSavingUs::
    .string "תודה שהצלת אותנו!$"

SilphCo_8F_Text_Grunt1Intro::
    .string "זה עד כאן בשבילך!$"

SilphCo_8F_Text_Grunt1Defeat::
    .string "לא היה מספיק אומץ!$"

SilphCo_8F_Text_Grunt1PostBattle::
    .string "אם לא תחזור…\n"
    .string "אני אקרא לחיזוק!$"

SilphCo_8F_Text_ParkerIntro::
    .string "אתה גורם לנו צרות!$"

SilphCo_8F_Text_ParkerDefeat::
    .string "הו?\n"
    .string "הפסדתי?$"

SilphCo_8F_Text_ParkerPostBattle::
    .string "אז, מה דעתך על המבוך של\n"
    .string "בניין ארגון סילף?$"

SilphCo_8F_Text_Grunt2Intro::
    .string "אני אחד מ4 האחים של צוות רוקט!\n"
    .string "$"

SilphCo_8F_Text_Grunt2Defeat::
    .string "ווו!\n"
    .string "אחים!$"

SilphCo_8F_Text_Grunt2PostBattle::
    .string "אני משאיר אותך לאחים שלי.$"

SilphCo_8F_Text_FloorSign::
    .string "ארגון סילף. משרד ראשי\n"
    .string "קומה 8$"

SilphCo_8F_Text_ToRocketBossMonsAreTools::
    .string "הבוס של צוות רוקט אכזרי מאוד!\p"
    .string "בשבילו, פוקימונים הם רק כלים\n"
    .string "לשימוש.\p"
    .string "מה יקרה אם הדיקטטור הזה\n"
    .string "ישתלט על החברה שלנו…$"
