SSAnne_2F_Room4_Text_LamarIntro::
    .string "איזה פוקימון אתה מעדיף,\n"
    .string "חזק או נדיר?$"

SSAnne_2F_Room4_Text_LamarDefeat::
    .string "אני חייב להצדיע לך!$"

SSAnne_2F_Room4_Text_LamarPostBattle::
    .string "באופן אישי, אני מעדיף פוקימונים\n"
    .string "חזקים ונדירים.$"

SSAnne_2F_Room4_Text_DawnIntro::
    .string "לא נראה לי שראיתי אותך\n"
    .string "במסיבה?$"

SSAnne_2F_Room4_Text_DawnDefeat::
    .string "קח את זה בקלות!$"

SSAnne_2F_Room4_Text_DawnPostBattle::
    .string "אה, אני מעריצה את הפוקימונים\n"
    .string "החזקים שלך! כמה אני מקנאה בך!$"
