PokemonTower_4F_Text_PaulaIntro::
    .string "רוח! לא!\n"
    .string "קוואה!$"

PokemonTower_4F_Text_PaulaDefeat::
    .string "איפה הרוח?$"

PokemonTower_4F_Text_PaulaPostBattle::
    .string "בטח חלמתי…$"

PokemonTower_4F_Text_LaurelIntro::
    .string "היקולל איתי!\n"
    .string "קוואה!$"

PokemonTower_4F_Text_LaurelDefeat::
    .string "מה!$"

PokemonTower_4F_Text_LaurelPostBattle::
    .string "אנחנו לא מצליחים לזהות\n"
    .string "את הרוחות…$"

PokemonTower_4F_Text_JodyIntro::
    .string "הוהוהו…\n"
    .string "אל תביס אותי!$"

PokemonTower_4F_Text_JodyDefeat::
    .string "הממ?\n"
    .string "מי? מה?$"

PokemonTower_4F_Text_JodyPostBattle::
    .string "שהפוקימונים המתים\n"
    .string "ינוחו בשלום…$"
