LavenderTown_Mart_Text_SearchingForStatRaiseItems::
    .string "אני מחפש פריטים שמעלים את\n"
    .string "הנתונים של פוקימונים.\p"
    .string "הם יעילים במהלך קרב יחיד בלבד.\p"
    .string "אני מחפש X התקפה, X הגנה, \n"
    .string "X מהירות, ו-X התקפה מיוחדת.\p"
    .string "אתה יודע איפה אפשר להשיג אותם?$"

LavenderTown_Mart_Text_DidYouBuyRevives::
    .string "קנית כבר החייאה?\n"
    .string "הם מחזירים פוקימון שהתעלף לחיים!$"

LavenderTown_Mart_Text_TrainerDuosCanChallengeYou::
    .string "לפעמים צמד מאמנים עשוי לאתגר\n"
    .string "אותך עם שני פוקימונים בו זמנית.\p"
    .string "במקרה כזה, תצטרך להוציא שני\n"
    .string "פוקימונים לקרב גם כן.$"

LavenderTown_Mart_Text_SoldNuggetFromMountainsFor5000::
    .string "この　あいだ　やまおくで\n"
    .string "きんのたまを　ひろい　ましてね！\p"
    .string "つかえない　しなもの　ですが\n"
    .string "うったら　なんと　5000¥でした$"
