SaffronCity_Dojo_Text_MasterKoichiIntro::
    .string "גרונט!\p"
    .string "אני המאסטר של קראטה!\n"
    .string "אני המנהיג כאן!\p"
    .string "אתה רוצה לאתגר אותנו?\n"
    .string "אל תצפה לרחמים!\p"
    .string "פוואה!$"

SaffronCity_Dojo_Text_MasterKoichiDefeat::
    .string "חווא!\n"
    .string "ארר! הובסתי!$"

SaffronCity_Dojo_Text_ChoosePrizedFightingMon::
    .string "אכן, הפסדתי!\p"
    .string "אבל אני מבקש ממך, אל תקח את\n"
    .string "הסמל שלנו כגביע!\p"
    .string "בתמורה, אתן לך פוקימון קרב\n"
    .string "יקר ערך!\p"
    .string "בחר איזה שאתה רוצה!$"

SaffronCity_Dojo_Text_StayAndTrainWithUs::
    .string "גרונט!\n"
    .string "הישאר והתאמן בקראטה איתנו!$"

SaffronCity_Dojo_Text_MikeIntro::
    .string "הוארך!\n"
    .string "תוריד את הנעליים!$"

SaffronCity_Dojo_Text_MikeDefeat::
    .string "אני נכנע!$"

SaffronCity_Dojo_Text_MikePostBattle::
    .string "חכה עד שתראה את המאסטר שלנו!\n"
    .string "אני קטן יחסית אליו!$"

SaffronCity_Dojo_Text_HidekiIntro::
    .string "שמעתי שאתה טוב!\n"
    .string "תראה לי!$"

SaffronCity_Dojo_Text_HidekiDefeat::
    .string "שופט!\n"
    .string "נקודה אחת!$"

SaffronCity_Dojo_Text_HidekiPostBattle::
    .string "המאסטר שלנו הוא לוחם מקצועי.\n"
    .string "תתכונן להפסיד!$"

SaffronCity_Dojo_Text_AaronIntro::
    .string "הייה!\n"
    .string "אני לא מפחד משום דבר קשה!\p"
    .string "אני מרסק סלעים באימונים\n"
    .string "כל יום!$"

SaffronCity_Dojo_Text_AaronDefeat::
    .string "יואו!\n"
    .string "אצבעות דפוקות!$"

SaffronCity_Dojo_Text_AaronPostBattle::
    .string "הדבר היחיד שמפחיד אותנו זה\n"
    .string "כוחות נפשיים!$"

SaffronCity_Dojo_Text_HitoshiIntro::
    .string "חוואה!\p"
    .string "אתה פולש לדוג'ו הקראטה שלנו!$"

SaffronCity_Dojo_Text_HitoshiDefeat::
    .string "אוף!\n"
    .string "אני נכנע!$"

SaffronCity_Dojo_Text_HitoshiPostBattle::
    .string "הלוחמים הטובים בארץ מתאמנים\n"
    .string "כאן.$"

SaffronCity_Dojo_Text_YouWantHitmonlee::
    .string "אתה רוצה את הבעיטה החזקה של\n"
    .string "היטמונלי?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster::
    .string "{PLAYER} קיבל את {STR_VAR_1}\n"
    .string "מהמאסטר של הקראטה.$"

SaffronCity_Dojo_Text_YouWantHitmonchan::
    .string "אתה רוצה את האגרופים החזקים\n"
    .string "של היטמונצ'אן?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster2::
    .string "{PLAYER} קיבל את {STR_VAR_1} מהמאסטר של הקראטה!$"

SaffronCity_Dojo_Text_BetterNotGetGreedy::
    .string "אל תתנהג בחמדנות…$"

SaffronCity_Dojo_Text_EnemiesOnEverySide::
    .string "אויבים בכל צד!$"

SaffronCity_Dojo_Text_GoesAroundComesAround::
    .string "מה שמסתובב מגיע בחזרה.$"

SaffronCity_Dojo_Text_FightingDojo::
    .string "דוג'ו קראטה$"
