Text_ObtainedTheX::
	.string "קיבלת את ה{STR_VAR_2}!$"

Text_BagIsFull::
	.string "התיק מלא...$"

Text_PutItemAway::
	.string "{PLAYER} שם את ה{STR_VAR_2}\n"
	.string "ב{STR_VAR_3}.$"

Text_FoundOneItem::
	.string "{PLAYER} מצא {STR_VAR_2} אחד!$"

Text_TooBadBagFull::
	.string "חבל!\n"
	.string "התיק מלא...$"

Text_FoundXCoins::
	.string "{PLAYER} מצא\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

Text_PutCoinsAwayInCoinCase::
	.string "{PLAYER} שם את המטבעות\n"
	.string "בארנק המטבעות.$"

Text_CoinCaseIsFull::
	.string "חבל!\n"
	.string "ארנק המטבעות מלא...$"

Text_NothingToPutThemIn::
	.string "חבל!\n"
	.string "אין לאן לשים אותם...$"

Text_FoundXItems::
	.string "{PLAYER} מצא\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

Text_ObtainedTheDecor::
	.string "קיבלת את ה{STR_VAR_2}!$"

Text_NoRoomForAnotherDecor::
	.string "חבל! אין מקום נוסף\n"
	.string "ל{STR_VAR_2} אחר...$"

Text_DecorTransferredToPC::
	.string "ה{STR_VAR_2} הועבר\n"
	.string "למחשב.$"
