Text_MonSentToBoxInSomeonesPC::
    .string "{STR_VAR_2} הועבר למחשב\n"
    .string "של מישהו.\p"
    .string "הוא הונח בתיבה\n"
    .string "{STR_VAR_1}.$"

Text_MonSentToBoxInBillsPC::
    .string "{STR_VAR_2} הועבר למחשב\n"
    .string "של ביל.\p"
    .string "הוא הונח בתיבה\n"
    .string "{STR_VAR_1}.$"

Text_MonSentToBoxSomeonesBoxFull::
    .string "תיבה {STR_VAR_3} במחשב\n"
    .string "של מישהו מלאה.\p"
    .string "{STR_VAR_2} הועבר\n"
    .string "לתיבה {STR_VAR_1}.$"

Text_MonSentToBoxBillsBoxFull::
    .string "תיבה {STR_VAR_3} במחשב\n"
    .string "של ביל מלאה.\p"
    .string "{STR_VAR_2} הועבר\n"
    .string "לתיבה {STR_VAR_1}.$"

Text_PlayerObtainedTheMon::
    .string "{PLAYER} קיבל את\n"
    .string "{STR_VAR_1}!$"

@ Unused. Translated below
@ You cannot carry any more Pokemon, so {STR_VAR_2} was sent to PC Box {STR_VAR_1}!
Text_MonSentToBoxInPC::
    .string "ポケモンを　もちきれないので\n"
    .string "パソコンの　ボックス“{STR_VAR_1}”　に\l"
    .string "{STR_VAR_2}を　てんそうした！$"

Text_NoMoreRoomForPokemon::
    .string "אין יותר מקום לפוקימונים!\p"
    .string "תיבות הפוקימונים מלאות\n"
    .string "ולא יכולות לקבל יותר!$"
    