Text_MayIHelpYou::
	.string "שלום!\n"
	.string "?אפשר לעזור לך$"

Text_FillOutQuestionnaire::
	.string "יש כאן שאלון.\n"
	.string "?האם תרצה למלא אותו$"

Text_QuestionnaireThankYou::
	.string "תודה שהקדשת מזמנך\n"
	.string "למילוי השאלון שלנו.\p"
	.string "המשוב שלך ישמש\n"
	.string "להתייחסות עתידית.$"

Text_YouKnowThoseWords::
	.string "!או, שלום\n"
	.string "?אתה מכיר את המילים האלה\p"
	.string "זה אומר שאתה בטח יודע על\n"
	.string "מתנת המסתורין.\p"
	.string "מעכשיו, אתה אמור\n"
	.string "!לקבל מתנות מסתורין$"

Text_YouCanAccessMysteryGift::
	.string "ברגע שתשמור את המשחק, תוכל\n"
	.string "לגשת למתנת המסתורין.$"

Text_ThankYouForAccessingMysteryGift::
	.string "תודה על הגישה למערכת\n"
	.string "מתנת המסתורין.$"
