Text_OnlySkilledTrainersAllowedThrough::
	.string "רק מאמנים מיומנים באמת\n"
	.string "רשאים לעבור.\p"
	.string "אין לך עדיין את התג\n"
	.string "{STR_VAR_1}!$"

Text_CantLetYouPass::
	.string "חוקים זה חוקים.\n"
	.string "אני לא יכול לתת לך לעבור.$"

Text_OhThatsBadgeGoRightAhead::
	.string "אה! זה התג {STR_VAR_1}!\n"
	.string "בבקשה, המשך קדימה.$"

Text_OnlyPassWithBadgeDontHaveYet::
	.string "אתה יכול לעבור כאן רק אם יש לך\n"
	.string "את התג {STR_VAR_1}.\p"
	.string "אין לך עדיין את התג\n"
	.string "{STR_VAR_1}.\p"
	.string "אתה חייב להשיג אותו כדי להגיע\n"
	.string "לליגת הפוקימונים.$"

Text_OnlyPassWithBadgeOhGoAhead::
	.string "אתה יכול לעבור כאן רק אם יש לך\n"
	.string "את התג {STR_VAR_1}.\p"
	.string "אה! זה התג {STR_VAR_1}!{PAUSE_MUSIC}{PLAY_BGM}{MUS_LEVEL_UP}{PAUSE 0x60}{RESUME_MUSIC}\p"
	.string "אוקיי, אז.\n"
	.string "בבקשה, המשך קדימה.$"
