gText_WouldYouLikeToSaveTheGame::
	.string "אתה רוצה לשמור את המשחק?$"

gText_AlreadySaveFile_WouldLikeToOverwrite::
	.string "כבר קיימת שמירה של המשחק.\n"
	.string "זה בסדר לשמור במקומה?$"

gText_SavingDontTurnOffThePower::
	.string "שומר…\n"
	.string "אל תכבה את המשחק.$"

gText_PlayerSavedTheGame::
	.string "{PLAYER} שמר את המשחק.$"

gText_SaveFailed2::
	.string "セーブに　しっぱい　しました‥$"

gText_DifferentGameFile::
	.string "הזהרה!\p"
	.string "כבר קיימת שמירה\p"
	.string "אם תשמור עכשיו השמירה הקודמת\n"
	.string "וכל מה שהשגת בה\l"
	.string "ימחקו לגמרי.\p"
	.string "אתה בטוח שאתה רוצה לשמור\n"
	.string "עכשיו במקום השמירה הקודמת?$"
