LavenderTown_Text_DoYouBelieveInGhosts::
    .string "האם אתה מאמין ברוחות?$"

LavenderTown_Text_SoThereAreBelievers::
    .string "באמת?\n"
    .string "אז יש מאמינים…$"

LavenderTown_Text_JustImaginingWhiteHand::
    .string "חחח, כנראה שלא.\p"
    .string "היד הלבנה ההיא על הכתף שלך…\n"
    .string "אני רק מדמיין אותה.$"

LavenderTown_Text_TownKnownAsMonGraveSite::
    .string "העיר הזו ידועה כאתר קבורה\n"
    .string "לפוקימונים.\p"
    .string "שירותי זיכרון מתקיימים ב\n"
    .string "מגדל הפוקימונים.$"

LavenderTown_Text_GhostsAppearedInTower::
    .string "רוחות הופיעו במגדל הפוקימונים.\p"
    .string "אני חושב שהן רוחות של\n"
    .string "פוקימונים שהרוקטס הרגו.$"

LavenderTown_Text_TownSign::
    .string "עיר לבנדר\n"
    .string "העיר הסגולה הנעלה$"

LavenderTown_Text_SilphScopeNotice::
    .string "סילף סקופ חדש!\n"
    .string "הפוך את הבלתי נראה לגלוי!\p"
    .string "חברת סילף$"

LavenderTown_Text_VolunteerPokemonHouse::
    .string "בית המתנדבים לפוקימונים\n"
    .string "בלבנדר$"

LavenderTown_Text_PokemonTowerSign::
    .string "מגדל הפוקימונים\n"
    .string "להרגיע את רוחות הפוקימונים$"
