PokemonMansion_Text_PressSecretSwitchJP::
    .string "ひみつの　スイッチが　ある！\p"
    .string "おして　みますか？$"

PokemonMansion_Text_LetsTryIt::
    .string "おしてみよう！　‥ポチッとな$"

PokemonMansion_Text_GaveUpOnPressingSwitch::
    .string "おすのは　あきらめた$"

PokemonMansion_1F_Text_SimonIntro::
    .string "המקום הזה, כאילו, ענק!$"

PokemonMansion_1F_Text_SimonDefeat::
    .string "איה!$"

PokemonMansion_1F_Text_SimonPostBattle::
    .string "אני תוהה לאן השותף שלי הלך.$"

PokemonMansion_1F_Text_BraydonIntro::
    .string "המנטור שלי גר כאן פעם.$"

PokemonMansion_1F_Text_BraydonDefeat::
    .string "פיו!\n"
    .string "מדהים!$"

PokemonMansion_1F_Text_BraydonPostBattle::
    .string "אז, אתה תקוע?\n"
    .string "נסה לקפוץ משם!$"

PokemonMansion_1F_Text_MewGaveBirthToMewtwo::
    .string "יומן: 6 בפברואר\n"
    .string "מייו ילדה.\p"
    .string "קראנו לתינוק החדש מיוטו.$"
