LavenderTown_PokemonCenter_1F_Text_RocketsDoAnythingForMoney::
    .string "צוות רוקט יעשו הכול למען כסף!\p"
    .string "אין עבודה מלוכלכת מדי, מעשה\n"
    .string "נורא מדי או פשע מרושע מדי!$"

LavenderTown_PokemonCenter_1F_Text_CubonesMotherKilledByRockets::
    .string "ראיתי את אמא של קיובון מנסה\n"
    .string "לברוח מצוות רוקט.\p"
    .string "היא נהרגה בניסיון להימלט…$"

LavenderTown_PokemonCenter_1F_Text_PeoplePayForCuboneSkulls::
    .string "אתה יודע שמין הפוקימון קיובון\n"
    .string "לובש גולגולות, נכון?\p"
    .string "יש אנשים שמוכנים לשלם הרבה\n"
    .string "בשביל אחת כזו.$"
