PokemonTower_6F_Text_AngelicaIntro::
    .string "תני...לי...\n"
    .string "דם...$"

PokemonTower_6F_Text_AngelicaDefeat::
    .string "אה...!$"

PokemonTower_6F_Text_AngelicaPostBattle::
    .string "אני מרגישה אנמית וחלשה...$"

PokemonTower_6F_Text_EmiliaIntro::
    .string "ארף...\n"
    .string "קוואה!$"

PokemonTower_6F_Text_EmiliaDefeat::
    .string "משהו נפל!$"

PokemonTower_6F_Text_EmiliaPostBattle::
    .string "השיער שלי לא נשר!\n"
    .string "זו הייתה רוח רעה!$"

PokemonTower_6F_Text_JenniferIntro::
    .string "קה...קה...קה...\n"
    .string "קה...קה...קה!$"

PokemonTower_6F_Text_JenniferDefeat::
    .string "קיייי!$"

PokemonTower_6F_Text_JenniferPostBattle::
    .string "מה קורה כאן?$"

PokemonTower_6F_Text_BeGoneIntruders::
    .string "לכו מכאן...\n"
    .string "פולשים...$"

PokemonTower_6F_Text_GhostWasCubonesMother::
    .string "הרוח הייתה הנשמה המיוסרת\n"
    .string "של אמא של קיובון!$"

PokemonTower_6F_Text_MothersSpiritWasCalmed::
    .string "רוח האם נרגעה.\p"
    .string "היא עלתה לגן עדן...$"
