VermilionCity_Mart_Text_TeamRocketAreWickedPeople::
    .string "יש אנשים מרושעים שישתמשו\n"
    .string "בפוקימונים למעשים פליליים.\p"
    .string "צוות רוקט סוחר בפוקימונים נדירים,\n"
    .string "לדוגמה.\p"
    .string "הם גם נוטשים פוקימונים שאינם\n"
    .string "פופולריים או שנחשבים לחסרי תועלת.\p"
    .string "כאלה הם, האנשים הנוראיים\n"
    .string "של צוות רוקט.$"

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer::
    .string "אני חושב שפוקימונים יכולים להיות\n"
    .string "טובים או רעים. זה תלוי במאמן.$"
