SSAnne_B1F_Room4_Text_LeonardIntro::
    .string "אתה יודע מה אומרים על\n"
    .string "מלחים וקרבות!$"

SSAnne_B1F_Room4_Text_LeonardDefeat::
    .string "נכון!\n"
    .string "קרב טוב, חבר!$"

SSAnne_B1F_Room4_Text_LeonardPostBattle::
    .string "הההה!\n"
    .string "רוצה להיות מלח, חבר?$"

SSAnne_B1F_Room4_Text_DuncanIntro::
    .string "בוא, אז!\n"
    .string "הגאווה שלי כמלח בסכנה!$"

SSAnne_B1F_Room4_Text_DuncanDefeat::
    .string "הרוח שלך הטביעה אותי!$"

SSAnne_B1F_Room4_Text_DuncanPostBattle::
    .string "ראית את מאסטר הדיג ב\n"
    .string "עיר ורמיליון?$"
