Text_RockSlideTeach::
    .string "כשאתה על הר סלעי\n"
    .string "כמו זה, מפולות סלעים הן איום.\p"
    .string "אתה יכול לדמיין?\n"
    .string "סלעים מתגלגלים עליך?\p"
    .string "זה יהיה, כאילו, וואוווווווו!\n"
    .string "טרור מוחלט!\p"
    .string "אתה לא נראה מפוחד.\n"
    .string "רוצה לנסות להשתמש במפולת סלעים?$"

Text_RockSlideDeclined::
    .string "אה, אז אתה כן מפוחד אחרי הכל.$"

Text_RockSlideWhichMon::
    .string "איזה פוקימון אני אמור ללמד\n"
    .string "מפולת סלעים?$"

Text_RockSlideTaught::
    .string "זה יכול להיות מפחיד להשתמש בזה\n"
    .string "במנהרה הזו…$"

SeafoamIslands_B4F_Text_BouldersMightChangeWaterFlow::
    .string "רמז: סלעים עלולים לשנות את\n"
    .string "זרימת המים.$"

SeafoamIslands_B4F_Text_DangerFastCurrent::
    .string "סכנה\n"
    .string "זרם מהיר!$"
