CeladonCity_Condominiums_3F_Text_ImTheProgrammer::
    .string "אני?\n"
    .string "אני המתכנת!$"

CeladonCity_Condominiums_3F_Text_ImTheGraphicArtist::
    .string "אני המעצב\n"
    .string "אני ציירתי אותך!$"

CeladonCity_Condominiums_3F_Text_IWroteTheStory::
    .string "אני כתבתי את\n"
    .string "הסיפור! אריקה נהדרת, נכון?\p"
    .string "אני גם אוהב את מיסטי מאוד!\p"
    .string "אה, וגם סברינה, אני מחבב אותה\l"
    .string "מאוד!$"

CeladonCity_Condominiums_3F_Text_ImGameDesignerShowMeFinishedPokedex::
    .string "באמת?\p"
    .string "אני יוצר המשחק!\p"
    .string "השלמת הפוקדקס היא משימה קשה,\l"
    .string "אבל אל תתיאש!\p"
    .string "כשתסיים, חזור לספר לי!$"

CeladonCity_Condominiums_3F_Text_CompletedPokedexCongratulations::
    .string "ואו! מעולה!\n"
    .string "סיימת למלא את הפוקדקס שלך!\l"
    .string "ברכותיי! ...{}$"

CeladonCity_Condominiums_3F_Text_ItsTheGameProgram::
    .string "זו תוכנית המשחק!\n"
    .string "עדיף שלא לגעת בה כדי לא לגרום\l"
    .string "לתקלות במשחק!$"

CeladonCity_Condominiums_3F_Text_SomeonesPlayingGame::
    .string "מישהו כאן משחק\n"
    .string "במקום לעבוד!$"

CeladonCity_Condominiums_3F_Text_ItsScriptBetterNotLookAtEnding::
    .string "זה התסריט!\n"
    .string "אל תקרא! זה יקלקל לך את הסוף!$"

CeladonCity_Condominiums_3F_Text_GameFreakDevelopmentRoom::
    .string "גיים פריק\n"
    .string "חדר פיתוח$"