FiveIsland_Text_IslandSign::
    .string "אי מספר 5\n"
    .string "האי כרונו: לאן שהזמן הולך$"

FiveIsland_Text_WeirdBuildingInMeadow::
    .string "אוף איזה באסה. רצית לשחק\n"
    .string "באחו.\p"
    .string "אבל בנו עליו איזה בניין מוזר,\n"
    .string "אז אני לא יכול לשחק שם.$"

FiveIsland_Text_BeenGettingBusierAroundHere::
    .string "הולך ונהיה פה יותר\n"
    .string "עמוס פה לאחרונה.\p"
    .string "ואני גם לא מצליח לתפוס פה דגים\n"
    .string "איכותיים בזמן האחרון.$"

