CeladonCity_DepartmentStore_5F_Text_ExplainStatEnhancers::
    .string "זו החנות היחידה\n"
    .string "שמוכרת ויטמינים משפרי ביצועים...\l"
    .string "לפוקימונים, כמובן.\p"
    .string "שימוש בסידן יגביר\n"
    .string "את היכולת המיוחדת של הפוקימון.\p"
    .string "שימוש בפחמן יגביר את המהירות.$"

CeladonCity_DepartmentStore_5F_Text_HereForStatEnhancers::
    .string "אני כאן כדי לקנות\n"
    .string "משפרי ביצועים לפוקימונים.\p"
    .string "חלבון יגביר את כוח המתקפה של\l"
    .string "הפוקימון.\p"
    .string "ברזל יגביר את ההגנה!$"

CeladonCity_DepartmentStore_5F_Text_Drugstore::
    .string "ק5: בית מרקחת$"

