RocketHideout_B4F_Text_GiovanniIntro::
    .string "אז! אני חייב לומר, אני מתרשם\n"
    .string "שהגעת לכאן.\p"
    .string "צוות רוקט לוכד פוקימונים\n"
    .string "מכל העולם.\p"
    .string "הם כלים חשובים להמשך\n"
    .string "העסקים הפליליים שלנו.\p"
    .string "אני המנהיג, ג'ובאני!\p"
    .string "על החוצפה שלך, תחווה\n"
    .string "עולם של כאב!$"

RocketHideout_B4F_Text_GiovanniDefeat::
    .string "מה!\n"
    .string "זה לא יכול להיות!$"

RocketHideout_B4F_Text_GiovanniPostBattle::
    .string "אני רואה שאתה מגדל פוקימונים\n"
    .string "בטיפול מקסימלי.\p"
    .string "ילד כמוך לעולם לא יבין\n"
    .string "מה אני מקווה להשיג.\p"
    .string "אני אפנה את הדרך הפעם!\p"
    .string "אני מקווה שניפגש שוב...$"

RocketHideout_B4F_Text_Grunt2Intro::
    .string "אני מכיר אותך!\n"
    .string "הרסת את התוכניות שלנו בהר הירח!$"

RocketHideout_B4F_Text_Grunt2Defeat::
    .string "נשרפתי שוב!$"

RocketHideout_B4F_Text_Grunt2PostBattle::
    .string "יש לך משהו נגד צוות\n"
    .string "רוקט?$"

RocketHideout_B4F_Text_Grunt3Intro::
    .string "איך אתה לא רואה את היופי\n"
    .string "של הרוע שלנו?$"

RocketHideout_B4F_Text_Grunt3Defeat::
    .string "איהיה!$"

RocketHideout_B4F_Text_Grunt3PostBattle::
    .string "בוס!\n"
    .string "אני מצטער שנכשלתי!$"

RocketHideout_B4F_Text_Grunt1Intro::
    .string "המעלית לא עובדת?\n"
    .string "למי יש את מפתח המעלית?$"

RocketHideout_B4F_Text_Grunt1Defeat::
    .string "לא!$"

RocketHideout_B4F_Text_Grunt1PostBattle::
    .string "אוי, לא!\n"
    .string "הפלתי את מפתח המעלית!$"
