SafariZone_North_Text_RestHouse::
    .string "בית מנוחה$"

SafariZone_North_Text_SecretHouseStillAhead::
    .string "טיפים למאמנים\p"
    .string "הבית הסודי עדיין לפניך.$"

SafariZone_North_Text_Area2::
    .string "אזור 2$"

SafariZone_North_Text_ZigzagThroughTallGrass::
    .string "טיפים לטריינר\p"
    .string "פוקימונים מתחבאים בעשב גבוה.\p"
    .string "עבור בזיגזג באזורים עשביים כדי\n"
    .string "לחשוף אותם.$"

SafariZone_North_Text_WinFreeHMFindSecretHouse::
    .string "טיפים לטריינר\p"
    .string "קבל מ”נ חינם על ידי מציאת ה\n"
    .string "הבית הסודי.$"
