CeruleanCity_House2_Text_RocketsStoleTMForDig::
    .string "צוות רוקט\n"
    .string "העלובים האלה!\p"
    .string "הסתכל מה הם עשו כאן!\p"
    .string "הם גנבו מ”מ שמלמד פוקימונים איך\l"
    .string "לחפור בורות!\p"
    .string "המ”מ הזה עלה לי הון! אני אומר לך,\l"
    .string "הון תועפות!$"

CeruleanCity_House2_Text_TeachDiglettDigWithoutTM::
    .string "חשבתי שמה שהלך\n"
    .string "כבר לא ישוב!\p"
    .string "החלטתי ללמד את דיגלט איך לחפור\l"
    .string "בלי מ”מ!$"

CeruleanCity_House2_Text_TeamRocketTryingToDigIntoNoGood::
    .string "צוות רוקט בטח\n"
    .string "מנסים לחפור לעצמם בורות מלאים\l"
    .string "בצרות!$"

CeruleanCity_House2_Text_TeamRocketLeftWayOut::
    .string "צוות רוקט\n"
    .string "השאירו כאן דרך מילוט!$"
