LavenderTown_House1_Text_Cubone::
    .string "קיובון: קיארוגו!$"

LavenderTown_House1_Text_RocketsKilledCubonesMother::
    .string "הרוקטס האיומים האלה!\n"
    .string "הם לא ראויים לרחמים!\p"
    .string "אמא של קיובון המסכן הזה…\p"
    .string "היא נהרגה בזמן שניסתה לברוח\n"
    .string "מצוות רוקט.$"

LavenderTown_House1_Text_GhostOfPokemonTowerIsGone::
    .string "הרוח של מגדל הפוקימונים\n"
    .string "נעלמה!\p"
    .string "מישהו בטח הרגיע את רוחה\n"
    .string "החסרת מנוחה!$"
