SaffronCity_House_Text_DontLookAtMyLetter::
    .string "…תודה על שכתבת.\n"
    .string "אני מקווה לראותך בקרוב!\p"
    .string "…היי!\n"
    .string "אל תסתכל על המכתב שלי!$"

SaffronCity_House_Text_Pidgey::
    .string "פידג'י: קורוקו!$"

SaffronCity_House_Text_GettingCopycatPokeDoll::
    .string "החקיינית חמודה!\n"
    .string "אני אקנה לה בובת פוקימון.$"

SaffronCity_House_Text_ExplainPPUp::
    .string "נתנו לי מעלה נ”כ במתנה.\p"
    .string "משתמשים בזה כדי להגדיל את ה-נ”כ\n"
    .string "של מהלך של פוקימון.\p"
    .string "אני צריך להשתמש בזה על מהלך חזק\n"
    .string "עם מעט נ”כ.$"
