FiveIsland_House1_JPText_HusbandWentOffFishing::
    .string "こんばんの　おかずは\n"
    .string "ようい　しなくて　いいぞ！\p"
    .string "って　だんなが\n"
    .string "つりに　いったん　だけど‥\l"
    .string "しんじて　いいのかねえ$"

FiveIsland_House1_Text_HusbandWentOffFishing::
    .string "את לא צריכה להכין אוכל לארוחת\n"
    .string "ערב היום!\p"
    .string "...זה מה שבעלי אמר לי\n"
    .string "כשהוא יצא היום לדוג.\p"
    .string "אני לא בטוחה שאני יכולה לסמוך עליו\n"
    .string "שיעמוד בהבטחה הזו.$"

