PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
    .string "פוקימונים לומדים טכניקות חדשות\n"
    .string "כשהם גדלים.\p"
    .string "אך יש מהלכים שחייבים ללמד אותם\n"
    .string "על ידי אנשים.$"

PewterCity_House2_Text_MonsEasierCatchIfStatused::
    .string "פוקימון הופך קל יותר לתפיסה\n"
    .string "אם יש לו בעיית סטטוס.\p"
    .string "שינה, רעל, כוויה, או שיתוק…\n"
    .string "כל אלו יעילים.\p"
    .string "אך תפיסת פוקימונים היא לעולם\n"
    .string "לא בטוחה!$"
