PokemonLeague_LoreleisRoom_Text_Intro::
    .string "ברוכים הבאים לליגת הפוקימון.\p"
    .string "אני לורליי מהרביעייה העילית.\p"
    .string "אף אחד לא יכול לנצח אותי כשזה\n"
    .string "נוגע לפוקימוני קרח.\p"
    .string "מהלכי הקפאה הם חזקים.\p"
    .string "הפוקימונים שלך יהיו לחסדי\n"
    .string "כשהם יקפאו לגמרי.\p"
    .string "הההה!\n"
    .string "אתה מוכן?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_RematchIntro::
    .string "ברוכים הבאים לליגת הפוקימון.\p"
    .string "אני, לורליי מהרביעייה העילית,\n"
    .string "חזרתי!\p"
    .string "אתה יודע איך זה הולך.\n"
    .string "אף אחד לא יכול לנצח אותי כשזה\l"
    .string "נוגע לפוקימוני קרח.\p"
    .string "מהלכי הקפאה הם חזקים.\p"
    .string "הפוקימונים שלך יהיו לחסדי\n"
    .string "כשהם יקפאו לגמרי.\p"
    .string "הההה!\n"
    .string "אתה מוכן?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_Defeat::
    .string "…זה לא אמור להיות ככה!$"

PokemonLeague_LoreleisRoom_Text_PostBattle::
    .string "אתה טוב יותר ממה שחשבתי.\n"
    .string "המשך קדימה.\p"
    .string "רק טעמת מהכוח של\n"
    .string "ליגת הפוקימון.$"
