SSAnne_1F_Room2_Text_TylerIntro::
    .string "אני אוהב פוקימונים!\n"
    .string "גם אתה?$"

SSAnne_1F_Room2_Text_TylerDefeat::
    .string "וואו!\n"
    .string "אתה מעולה!$"

SSAnne_1F_Room2_Text_TylerPostBattle::
    .string "תקשיב, תקשיב!\n"
    .string "בוא נהיה חברים, בסדר?\p"
    .string "אז נוכל להחליף פוקימונים\n"
    .string "ולעשות דברים ביחד.$"

SSAnne_1F_Room2_Text_AnnIntro::
    .string "אספתי את הפוקימונים האלה\n"
    .string "מכל העולם!$"

SSAnne_1F_Room2_Text_AnnDefeat::
    .string "אוי, לא!\n"
    .string "הסתובבתי בעולם בשביל אלה!$"

SSAnne_1F_Room2_Text_AnnPostBattle::
    .string "פגעת בפוקימונים המסכנים שלי!\p"
    .string "אני דורשת שתטפל בהם\n"
    .string "במרכז הפוקימונים!$"

SSAnne_1F_Room2_Text_CruisingAroundWorld::
    .string "אנחנו מסתובבים בעולם,\n"
    .string "הילדים שלי ואני.$"
