Route21_North_Text_RonaldIntro::
	.string "רוצה לדעת אם הדגים נושכים?$"

Route21_North_Text_RonaldDefeat::
	.string "אוי, לא!$"

Route21_North_Text_RonaldPostBattle::
	.string "אני לא מצליח לתפוס שום דבר טוב.\n"
	.string "אין אפילו פוקימון טוב אחד!$"

Route21_North_Text_WadeIntro::
	.string "עשיתי שלל גדול!\n"
	.string "רוצה לנסות להתמודד?$"

Route21_North_Text_WadeDefeat::
	.string "חה חה, נראה שמג'יקארפ פשוט\n"
	.string "לא עומד בסטנדרטים, נכון?$"

Route21_North_Text_WadePostBattle::
	.string "נראה שאני תופס רק מג'יקארפ!$"

Route21_North_Text_SpencerIntro::
	.string "הים מטהר את הגוף והנשמה שלי!$"

Route21_North_Text_SpencerDefeat::
	.string "אייה!$"

Route21_North_Text_SpencerPostBattle::
	.string "הים נהדר והכול, אבל אני אוהב\n"
	.string "גם את ההרים.$"


@ Below is the battle text for the Cue Ball that was on Route 21 in Gen 1.
@ This trainer wasnt used in Gen 3 so their text goes unused/untranslated
@ Interestingly they did add a rematch intro text for this trainer
@ English translations from RB are listed

@ "What's wrong with me swimming?"
Route21_North_Text_CueBallIntro::
	.string "おれだって　たまには\n"
	.string "およぎに　くるぜ！$"

@ "Cheap shot!"
Route21_North_Text_CueBallDefeat::
	.string "ぐわわ！$"

@ "I look like what? A studded inner tube? Get lost!"
Route21_North_Text_CueBallPostBattle::
	.string "うきやすそう　だと？\n"
	.string "うるせー　おおきな　おせわだッ！$"
