SilphCo_6F_Text_RocketsTookOverBuilding::
    .string "צוות רוקט באו והשתלטו על\n"
    .string "הבניין!$"

SilphCo_6F_Text_BetterGetBackToWork::
    .string "טוב, עדיף לחזור לעבודה.$"

SilphCo_6F_Text_HelpMePlease::
    .string "אוי לא, אוי לא.\n"
    .string "עזור לי, בבקשה!$"

SilphCo_6F_Text_WeGotEngaged::
    .string "השתגענו.\n"
    .string "ההה!$"

SilphCo_6F_Text_ThatManIsSuchACoward::
    .string "הגבר הזה לידם…\n"
    .string "הוא פחדן כל כך!$"

SilphCo_6F_Text_NeedsMeToLookAfterHim::
    .string "הוא כל כך חסר אונים, הוא היה\n"
    .string "צריך מישהו כמוני שיטפל בו.$"

SilphCo_6F_Text_RocketsTryingToConquerWorld::
    .string "צוות רוקט מנסה לכבוש\n"
    .string "את העולם עם פוקימונים.$"

SilphCo_6F_Text_RocketsRanAwayBecauseOfYou::
    .string "צוות רוקט ברחו, וזה הכל\n"
    .string "בגללך!$"

SilphCo_6F_Text_TargetedSilphForOurMonProducts::
    .string "הם כנראה התמקמו בארגון סילף\n"
    .string "בשביל מוצרי הפוקימון שלנו.$"

SilphCo_6F_Text_ComeWorkForSilphWhenYoureOlder::
    .string "בוא לעבוד בארגון סילף כשתהיה\n"
    .string "גדול יותר.$"

SilphCo_6F_Text_Grunt1Intro::
    .string "אני אחד מ-4 האחים של צוות רוקט!\n"
    .string "$"

SilphCo_6F_Text_Grunt1Defeat::
    .string "התפוצצתי!$"

SilphCo_6F_Text_Grunt1PostBattle::
    .string "לא אכפת לי!\n"
    .string "האחים שלי ינצחו אותי!$"

SilphCo_6F_Text_TaylorIntro::
    .string "הנשיא המסריח הזה!\p"
    .string "הגיע לו ששלחו אותי לסניף טיקסי!\p"
    .string "זו הסיבה שצוות רוקט באו אחרי\n"
    .string "אנחנו, אני בטוח בזה!$"

SilphCo_6F_Text_TaylorDefeat::
    .string "הו, לא!$"

SilphCo_6F_Text_TaylorPostBattle::
    .string "סניף טיקסי?\n"
    .string "הוא נמצא במרחבי רוסיה!$"

SilphCo_6F_Text_Grunt2Intro::
    .string "אתה מעז לבגוד ב-צוות רוקט?$"

SilphCo_6F_Text_Grunt2Defeat::
    .string "בוגד!$"

SilphCo_6F_Text_Grunt2PostBattle::
    .string "אם אתה תומך בצדק, אתה\n"
    .string "בוגד בנו הרעים!$"

SilphCo_6F_Text_FloorSign::
    .string "ארגון סילף. משרד ראשי\n"
    .string "קומה 6$"
