FuchsiaCity_PokemonCenter_1F_Text_CantBecomeGoodTrainerWithOneMon::
    .string "אי אפשר לנצח רק עם\n"
    .string "פוקימון אחד חזק.\p"
    .string "זה קשה, אבל אתה חייב לגדל אותם\l"
    .string "באופן שווה.$"

FuchsiaCity_PokemonCenter_1F_Text_PokemonLeagueWestOfViridian::
    .string "יש שביל צר מערבה\n"
    .string "מהעיר ורידיאן.\p"
    .string "הוא מוביל למפקדת ליגת הפוקימון.\l"
    .string "המפקדה מפקחת על כל המאמנים.$"

FuchsiaCity_PokemonCenter_1F_Text_VisitSafariZoneForPokedex::
    .string "אם אתה עובד על למלא את הפוקידקס,\n"
    .string "תבקר באיזור הספארי.\p"
    .string "יש שם המון סוגים של\n"
    .string "פוקימונים.$"

