SaffronCity_Text_WhatDoYouWantGetLost::
    .string "מה אתה רוצה?\n"
    .string "'תחפף!$"

SaffronCity_Text_BossTakeTownForTeamRocket::
    .string "הבוס אמר שהוא\n"
    .string "ישתלט על העיר!$"

SaffronCity_Text_DontGetDefiantOrIllHurtYou::
    .string "זוז לי מבילך!$"

SaffronCity_Text_SaffronBelongsToTeamRocket::
    .string "העיר ספרון שייכת\n"
    .string "לצוות רוקט!$"

SaffronCity_Text_CriminalLifeMakesMeFeelAlive::
    .string "רשע גורם לי להרגיש\n"
    .string "כל כך... חי!$"

SaffronCity_Text_WatchWhereYoureWalking::
    .string "אווץ'! שים לב איפה\n"
    .string "אתה דורך!$"

SaffronCity_Text_WeCanExploitMonsAroundWorld::
    .string "עכשיו שסילף תחת\n"
    .string "שליטתנו, נוכל לנצל פוקימונים\l"
    .string "ברחבי העולם כולו!$"

SaffronCity_Text_YouBeatTeamRocket::
    .string "הבסת את צוות\n"
    .string "רוקט לגמרי לבד? זה מדהים!$"

SaffronCity_Text_SafeToGoOutAgain::
    .string "כן! צוות\n"
    .string "רוקט נעלם! זה בטוח לצאת\l"
    .string "החוצה שוב!$"

SaffronCity_Text_PeopleComingBackToSaffron::
    .string "אנשים בטוח ינהרו\n"
    .string "חזרה לזעפרן עכשיו.$"

SaffronCity_Text_FlewHereOnPidgeot::
    .string "עפתי לפה על\n"
    .string "הפידג'יוט שלי כשקראתי על סילף.\p"
    .string "זה כבר נגמר? פספסתי את סערת\l"
    .string "התקשורת?$"

SaffronCity_Text_Pidgeot::
    .string "פידג'יוט: בי ביביי!$"

SaffronCity_Text_SawRocketBossEscaping::
    .string "ראיתי את מפקד\n"
    .string "צוות רוקט בורח מבניין סילף.$"

SaffronCity_Text_ImASecurityGuard::
    .string "אני מאבטח.\p"
    .string "אני לא מרשה לילדים חשודים להכנס!$"

SaffronCity_Text_HesTakingASnooze::
    .string "...\n"
    .string "נחרה...\p"
    .string "הא! הוא תופס תנומה!$"

SaffronCity_Text_CitySign::
    .string "העיר ספרון\n"
    .string "ארץ המסחר הזהובה והנוצצת$"

SaffronCity_Text_FightingDojo::
    .string "מאסטר הלחימה$"

SaffronCity_Text_GymSign::
    .string "העיר ספרון\n"
    .string "מכון פוקימונים מנהלת: סברינה\p"
    .string "המאסטר של פוקימוני על-חושי!$"

SaffronCity_Text_FullHealCuresStatus::
    .string "טיפים למאמנים\p"
    .string "ריפוי מלא מרפא את כל סוגי\l"
    .string "החוליים, כמו שינה וכוויה.\p"
    .string "זה עולה קצת יותר, אבל זה\l"
    .string "יותר נוח.$"

SaffronCity_Text_GreatBallImprovedCatchRate::
    .string "טיפים למאמנים\p"
    .string "לכדורי רב החדשים יש שיעור תפיסה\l"
    .string "משופר.\p"
    .string "נסה את זה על פוקימונים קשים\l"
    .string "לתפיסה.$"

SaffronCity_Text_SilphCoSign::
    .string "סילף בע”מ\n"
    .string "בניין משרדים$"

SaffronCity_Text_MrPsychicsHouse::
    .string "ביתו של מר\n"
    .string "על חושי$"

SaffronCity_Text_SilphsLatestProduct::
    .string "המוצר החדש\n"
    .string "של סילף!\p"
    .string "בקרוב...$"

SaffronCity_Text_TrainerFanClubSign::
    .string "מועדון מעריצי מאמני פוקימון\p"
    .string "הרבה מאמנים קשקשו את שמותיהם\n"
    .string "על השלט הזה.$"

SaffronCity_Text_HowCanClubNotRecognizeLance::
    .string "המועדון הזה…\n"
    .string "אין לאף אחד פה מושג!\p"
    .string "איך הם לא מזהים את\n"
    .string "הגאונות של לאנס?\p"
    .string "הוא מייצג צדק!\n"
    .string "הוא מגניב, ובו זמנית נלהב!\l"
    .string "הוא הכי גדול, לאנס!$"
