Route6_Text_RickyIntro::
    .string "מי שם?\n"
    .string "תפסיק להאזין לנו!$"

Route6_Text_RickyDefeat::
    .string "אני פשוט לא יכול לנצח!$"

Route6_Text_RickyPostBattle::
    .string "לחש…\n"
    .string "לחש…$"

Route6_Text_NancyIntro::
    .string "סלח לי!\n"
    .string "זו שיחה פרטית!$"

Route6_Text_NancyDefeat::
    .string "אוף!\n"
    .string "אני שונאת להפסיד.$"

Route6_Text_NancyPostBattle::
    .string "לחש…\n"
    .string "לחש…$"

Route6_Text_KeigoIntro::
    .string "אין הרבה חרקים כאן.$"

Route6_Text_KeigoDefeat::
    .string "לא!\n"
    .string "אתה צוחק!$"

Route6_Text_KeigoPostBattle::
    .string "אני אוהב חרקים, אז אני חוזר ליער\n"
    .string "וירידיאן.$"

Route6_Text_JeffIntro::
    .string "אה?\n"
    .string "אתה רוצה לדבר איתי?$"

Route6_Text_JeffDefeat::
    .string "זה מסריח…\n"
    .string "לא יכולתי לנצח את האתגר שלך…$"

Route6_Text_JeffPostBattle::
    .string "אני צריך להביא יותר פוקימונים\n"
    .string "איתי. אני ארגיש יותר בטוח כך.$"

Route6_Text_IsabelleIntro::
    .string "אני?\n"
    .string "טוב, בסדר. אני אשחק!$"

Route6_Text_IsabelleDefeat::
    .string "זה פשוט לא עבד…$"

Route6_Text_IsabellePostBattle::
    .string "אני רוצה להיות חזקה יותר.\n"
    .string "מה הסוד שלך?$"

Route6_Text_ElijahIntro::
    .string "לא ראיתי אותך בסביבה.\n"
    .string "אתה טוב?$"

Route6_Text_ElijahDefeat::
    .string "אתה טוב מדי!$"

Route6_Text_ElijahPostBattle::
    .string "האם הפוקימונים שלי חלשים?\n"
    .string "או שאני פשוט גרוע?\l"
    .string "מה אתה חושב?$"

Route6_Text_UndergroundPathSign::
    .string "דרך תת קרקעית\n"
    .string "עיר סרוליאן - עיר ורמיליון$"
