PewterCity_PokemonCenter_1F_Text_TeamRocketMtMoonImOnPhone::
    .string "מה!?\p"
    .string "צוות רוקט בהר הירח?\n"
    .string "הא?\p"
    .string "אני בטלפון!\n"
    .string "הסתלק!$"

PewterCity_PokemonCenter_1F_Text_Jigglypuff::
    .string "ג'יגליפאף: פו פופו!$"

PewterCity_PokemonCenter_1F_Text_WhenJiggylypuffSingsMonsGetDrowsy::
    .string "פיהוק!\p"
    .string "כשג'יגליפאף שרה, פוקימונים\n"
    .string "מתחילים להתעייף…\p"
    .string "…גם אני…\n"
    .string "נחירות…$"

PewterCity_PokemonCenter_1F_Text_TradingMyClefairyForPikachu::
    .string "אני ממש רוצה פיקאצ'ו, אז אני\n"
    .string "מחליף את הקלפרי שלי באחד.$"

PewterCity_PokemonCenter_1F_Text_TradingPikachuWithKid::
    .string "אני מחליף פוקימונים עם הילד\n"
    .string "ההוא שם.\p"
    .string "היו לי שני פיקאצ'ו, אז חשבתי\n"
    .string "שכדאי להחליף אחד.$"
