SSAnne_B1F_Room1_Text_PhillipIntro::
    .string "חבר, אתה הולך על הקרש אם\n"
    .string "תפסיד!$"

SSAnne_B1F_Room1_Text_PhillipDefeat::
    .string "ארג!\n"
    .string "הובס על ידי ילד!$"

SSAnne_B1F_Room1_Text_PhillipPostBattle::
    .string "כשאנחנו בים, פוקימוני מדוזות\n"
    .string "לפעמים צפים על פני המים.$"

SSAnne_B1F_Room1_Text_BarnyIntro::
    .string "שלום, זר!\p"
    .string "אני לא יכול לדעת אם אתה מהים\n"
    .string "או מההרים, אבל בוא נדבר.\p"
    .string "כל הפוקימונים שלי הם מהים.$"

SSAnne_B1F_Room1_Text_BarnyDefeat::
    .string "לעזאזל!\n"
    .string "הניחה לו לברוח!$"

SSAnne_B1F_Room1_Text_BarnyPostBattle::
    .string "עמדתי למנות אותך\n"
    .string "לעוזר שלי!$"
