SSAnne_1F_Corridor_Text_LeStrongSilentType::
    .string "בונז'ור!\n"
    .string "אני המלצר בספינה הזו!\p"
    .string "אשמח להגיש לך\n"
    .string "כל מה שתרצה!\p"
    .string "… … …\n"
    .string "אה! הטיפוס החזק והשקט!$"

SSAnne_1F_Corridor_Text_PassengersAreRestless::
    .string "הנוסעים חסרי מנוחה\n"
    .string "מהמסע הארוך הזה.\p"
    .string "ייתכן שתתמודד עם\n"
    .string "המשתעממים יותר!$"
