PokemonTower_3F_Text_HopeIntro::
    .string "אררר… אוואה…\n"
    .string "הוהו… גרא…$"

PokemonTower_3F_Text_HopeDefeat::
    .string "הואה!\n"
    .string "ניצלתי!$"

PokemonTower_3F_Text_HopePostBattle::
    .string "אפשר לזהות את הרוחות\n"
    .string "בעזרת משקפת סילף.$"

PokemonTower_3F_Text_CarlyIntro::
    .string "קקקק…\n"
    .string "קוואה!$"

PokemonTower_3F_Text_CarlyDefeat::
    .string "הממ?\n"
    .string "מה אני עושה?$"

PokemonTower_3F_Text_CarlyPostBattle::
    .string "סליחה!\n"
    .string "הייתי אחוזת דיבוק!$"

PokemonTower_3F_Text_PatriciaIntro::
    .string "לכי מכאן!\n"
    .string "רוח רעה!$"

PokemonTower_3F_Text_PatriciaDefeat::
    .string "פיו!\n"
    .string "הרוח עזבה!$"

PokemonTower_3F_Text_PatriciaPostBattle::
    .string "האחרים למעלה…\n"
    .string "בטח גם הם אחוזי דיבוק.$"
