SilphCo_9F_Text_YouShouldTakeQuickNap::
    .string "אתה נראה עייף.\n"
    .string "אתה צריך לקחת מנוחה קצרה.$"

SilphCo_9F_Text_DontGiveUp::
    .string "אל תוותר!$"

SilphCo_9F_Text_ThankYouSoMuch::
    .string "תודה רבה!$"

SilphCo_9F_Text_Grunt1Intro::
    .string "הפוקימונים שלך נראים מאוד\n"
    .string "מעריצים אותך, ילד!$"

SilphCo_9F_Text_Grunt1Defeat::
    .string "גאהה!$"

SilphCo_9F_Text_Grunt1PostBattle::
    .string "אם הייתי מתחיל כמאמן בגילך…$"

SilphCo_9F_Text_EdIntro::
    .string "לפוקימונים שלך יש נקודות תורפה!\n"
    .string "אני יכול לפגוע בהם!$"

SilphCo_9F_Text_EdDefeat::
    .string "הכנעת אותי!$"

SilphCo_9F_Text_EdPostBattle::
    .string "ניצול נקודות תורפה באמת עובד.\n"
    .string "תחשוב על יתרונות סוגי הפוקימונים.$"

SilphCo_9F_Text_Grunt2Intro::
    .string "אני אחד מ4 האחים של צוות רוקט!\n"
    .string "$"

SilphCo_9F_Text_Grunt2Defeat::
    .string "ווורג!\n"
    .string "אחים, הפסדתי!$"

SilphCo_9F_Text_Grunt2PostBattle::
    .string "האחים שלי ינקמו אותי!$"

SilphCo_9F_Text_FloorSign::
    .string "ארגון סילף. משרד ראשי\n"
    .string "קומה 9$"
