CinnabarIsland_Gym_Text_PhotoOfBlaineAndFuji::
    .string "זו תמונה של בליין\n"
    .string "וד”ר פוג'י.\p"
    .string "הם עומדים כתף אל כתף\n"
    .string "ומחייכים חיוך רחב.$"

CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively::
    .string "אנחנו חוקרים פה\n"
    .string "פוקימונים באופן נרחב.\p"
    .string "לעתים קרובות אנשים מביאים אלינו\l"
    .string "פוקימונים נדירים לבחינה.$"

CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji::
    .string "תמונה של מייסד המעבדה...\n"
    .string "ד”ר פוג'י?!$"

CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign::
    .string "מעבדת הפוקימון\n"
    .string "חדר ישיבות$"

CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign::
    .string "מעבדת הפוקימון\n"
    .string "חדר מו”פ$"

CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign::
    .string "מעבדת הפוקימון\n"
    .string "חדר בדיקות$"

