CeladonCity_House1_Text_SlotsReelInTheDough::
    .string "חה חה! מכונות\n"
    .string "המזל מרוויחות לנו בוכטות!$"

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
    .string "המפקד!\p"
    .string "בדיוק העברנו 0002 פוקימונים\l"
    .string "כפרסים במשחקי המזל!$"

CeladonCity_House1_Text_DontTouchGameCornerPoster::
    .string "אל תיגע\n"
    .string "בפוסטר שנמצא במשחקיית רוקט!\p"
    .string "זה לא שמתחבא מאחוריו איזה מתג\l"
    .string "סודי!$"

@ Text for the replaced altars in the rocket chiefs house / celadon mansion
@ In English RB, this is westernized as "It's a sculpture of DIGLETT.", and is removed altogether in FRLG
Text_ItsABuddhistAltar::
    .string "ぶつだん　だ‥$"
