gControlsGuide_Text_Intro::
    .string "הסבר על הכפתורים השונים\n"
    .string "לפי סדר החשיבות שלהם.$"

gControlsGuide_Text_DPad::
    .string "מזיז את הדמות הראשית.\n"
    .string "גם משמש כדי לבחור בין\n"
    .string "אפשריות שונות.$"

gControlsGuide_Text_AButton::
    .string "משמש כדי לאשר בחירה, לבדוק\n"
    .string "דברים, לשוחח, ולגלול טקסט.$"

gControlsGuide_Text_BButton::
    .string "משמש כדי לצאת, לבטל בחירה\n"
    .string "ולבטל מצב.$"

gControlsGuide_Text_StartButton::
    .string "לחץ על כפתור זה כדי לפתוח"
    .string "את התפריט.$"

gControlsGuide_Text_SelectButton::
    .string "משמש כדי להזיז חפצים וכדי\n"
    .string "להשתמש בחפצים שמורים.$"

gControlsGuide_Text_LRButtons::
    .string "אם אתה צריך עזרה תוך כדי\n"
    .string "המשחק, או על איך לעשות דברים,\n"
    .string "תלחץ על הכפתורים ש או י.$"

gOakSpeech_Text_AskPlayerGender::
    .string "עכשיו תגיד לי. אתה בן?\n"
    .string "או שאת בת?$"

gPikachuIntro_Text_Page1::
    .string "בעולם שאתה הולך להיכנס אליו\n"
    .string "אתה תצא להרפתקה גדולה,\n"
    .string "ואתה הגיבור המרכזי.\n"
    .string "\n"
    .string "תדבר עם אנשים ותבדוק דברים\n"
    .string "בכל מקום שאליו תלך, אם זה בערים,\n"
    .string "דרכים או מערות. תאסוף מידע ורמזים\n"
    .string "מכל מקור אפשרי.$"

gPikachuIntro_Text_Page2::
    .string "דרכים חדשות יפתחו בפניכם על ידי עזרה\n"
    .string "לאנשים, התגברות על אתגרים,\n"
    .string "ופתירת תעלומות.\n"
    .string "\n"
    .string "לפעמים אתה תהיה מאותגר על ידי\n"
    .string "אחרים ותותקף על ידי פוקימונים בטבע.\n"
    .string "תהיה אמיץ ותמשיך להתקדם קדימה.$"

gPikachuIntro_Text_Page3::
    .string "אנחנו מקווים שתוך כדי ההרפתקה שלך\n"
    .string "תתחבר לכל מיני אנשים ותרגיש את\n"
    .string "עצמך משתפר. זו המטרה הכי גדולה שלנו..\n"
    .string "\n"
    .string "תלחץ על כפתור הA\n"
    .string "ובוא נתחיל בהרפתקה!!$"

gOakSpeech_Text_WelcomeToTheWorld::
    .string "שלום!\n"
    .string "אני שמח לפגוש אותך!\p"
    .string "ברוך הבא לעולם הפוקימונים!\p"
    .string "שמי הוא פרופסור אוק.\p"
    .string "אתה גם יכול לקרוא לי\n"
    .string "פרופסור הפוקימונים.\p$"

gOakSpeech_Text_ThisWorld::
    .string ""

gOakSpeech_Text_IsInhabitedFarAndWide::
    .string "בכל רחבי העולם הזה\n"
    .string "יש פוקימונים.\p$"

gOakSpeech_Text_IStudyPokemon::
    .string "חלק מהאנשים מתייחסים\n"
	.string "לפוקימונים כחיות מחמד.\n"
    .string "יש כאלה שאוהבים להילחם בעזרתם.\p"
    .string "ואני...\p"
    .string "העבודה שלי היא ללמוד על פוקימונים.\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
    .string "אבל קודם, ספר לי\n"
    .string "קצת על עצמיך.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
    .string "בוא נתחיל עם השם.\n"
    .string "מה השם שלך?\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
    .string "נכון..\n"
    .string "שמך הוא {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName::
    .string "זה הנכד שלי.\p"
    .string "הוא ואתה יריבים\n"
    .string "מאז שהייתם תינוקות.\p"
    .string "תוכל להזכיר לי את השם שלו?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
    .string "השם של היריב שלך, מה הוא היה?$"

gOakSpeech_Text_ConfirmRivalName::
    .string "אמ.. קראו לו {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
    .string "נכון! עכשיו נזכרתי!\n"
    .string "קוראים לו {RIVAL}!\p$"

gOakSpeech_Text_LetsGo::
    .string "{PLAYER}!\p"
    .string "ההרפתקה האישית שלך\n"
    .string "עומדת להתחיל!\p"
    .string "עולם מלא בחלומות והרפתקאות\n"
    .string "עם פוקימונים מחכה!\n"
	.string "קדימה בוא נצא לדרך!$"
