SSAnne_2F_Corridor_Text_ThisShipIsLuxuryLiner::
    .string "הספינה הזו היא ספינת פאר\n"
    .string "למאמנים מכל העולם!\p"
    .string "בכל נמל, אנחנו עורכים מסיבות\n"
    .string "עם מאמנים מוזמנים.$"

SSAnne_2F_Corridor_Text_RivalIntro::
    .string "{RIVAL}: בונז'ור!\n"
    .string "{PLAYER}!\p"
    .string "מי היה מאמין שנפגש כאן!\n"
    .string "{PLAYER}, האם באמת הזמינו אותך?\p"
    .string "אז איך מתקדם הפוקידקס שלך?\p"
    .string "אני כבר תפסתי 40 סוגים, חבר.\n"
    .string "סוגים שונים נמצאים בכל מקום.\p"
    .string "זחל באזורים עם דשא,\n"
    .string "וחפש אותם היטב.$"

SSAnne_2F_Corridor_Text_RivalDefeat::
    .string "המפ!\p"
    .string "לפחות אתה מגדל את\n"
    .string "הפוקימונים שלך!$"

SSAnne_2F_Corridor_Text_RivalVictory::
    .string "{PLAYER}‥！\n"
    .string "ふなよい　してるのか！\p"
    .string "もっと　からだ\n"
    .string "きたえた　ほうが　いいぜ！$"

SSAnne_2F_Corridor_Text_RivalPostBattle::
    .string "{RIVAL}: שמעתי שיש על הסיפון\n"
    .string "אמן של חיתוך.\p"
    .string "אבל הוא היה רק זקן\n"
    .string "שסובל ממחלת ים!\p"
    .string "חיתוך עצמו הוא מאוד שימושי.\n"
    .string "כן, זה יהיה שימושי.\p"
    .string "גם אתה צריך ללכת לראות אותו.\n"
    .string "להתראות!$"
