Route10_Text_MarkIntro::
    .string "וואו, הגעת כל הדרך הנה?\n"
    .string "אולי גם אתה פוקימניאק?\l"
    .string "רוצה לראות את האוסף שלי?$"

Route10_Text_MarkDefeat::
    .string "הממ.\n"
    .string "אני לא כועס!$"

Route10_Text_MarkPostBattle::
    .string "יש לי עוד פוקימונים נדירים בבית!$"

Route10_Text_ClarkIntro::
    .string "הא-הא-ה-הא!$"

Route10_Text_ClarkDefeat::
    .string "הא-הא!\n"
    .string "לא צוחק!\l"
    .string "הא-חוות צינון! הא-הא-צ'ו!$"

Route10_Text_ClarkPostBattle::
    .string "הא-הא-צ'ו!\n"
    .string "הא-צ'ו!\l"
    .string "נחיר! נזלת!$"

Route10_Text_HermanIntro::
    .string "שלום, ילד!\n"
    .string "רוצה לראות את הפוקימונים שלי?$"

Route10_Text_HermanDefeat::
    .string "אוי, לא!\n"
    .string "הפוקימונים שלי!$"

Route10_Text_HermanPostBattle::
    .string "אני לא אוהב אותך.\n"
    .string "אני לא אוהב אף אחד יותר ממני!$"

Route10_Text_HeidiIntro::
    .string "הייתי בכמה אימונים במכון\n"
    .string "הפוקימונים …אבל תמיד אני מפסידה.$"

Route10_Text_HeidiDefeat::
    .string "אוי!\n"
    .string "אחרי כל האימונים שלי!$"

Route10_Text_HeidiPostBattle::
    .string "שמת לב לכמה פוקימניאקים\n"
    .string "פזורים פה?\p"
    .string "תוכל לדמיין? הם?\n"
    .string "פה בהרים?$"

Route10_Text_TrentIntro::
    .string "אה!\n"
    .string "האוויר ההררי הזה טעים!$"

Route10_Text_TrentDefeat::
    .string "זה פתח לי את הראש!$"

Route10_Text_TrentPostBattle::
    .string "אני מרגיש מנופח מאוויר הרים!$"

Route10_Text_CarolIntro::
    .string "אני מרגישה קצת סחוטה.\n"
    .string "לא יצא לי לטפס הרבה בזמן האחרון.$"

Route10_Text_CarolDefeat::
    .string "אני עייפה מדי.\n"
    .string "לא הייתי מוכנה לזה.$"

Route10_Text_CarolPostBattle::
    .string "הפוקימונים פה בהרים\n"
    .string "כל כך מסיביים…\p"
    .string "הייתי רוצה שיהיו פוקימונים ורודים\n"
    .string "עם דפוס פרחוני!$"

Route10_Text_RockTunnelDetourToLavender::
    .string "מנהרת אבן\n"
    .string "עקיפה לעיר לאבנדר$"

Route10_Text_RockTunnel::
    .string "מנהרת אבן$"

Route10_Text_PowerPlant::
    .string "תחנת כוח$"
