LavenderTown_PokemonCenter_1F_Text_HearMrFujiNotFromAroundHere::
    .string "עברתי לאחרונה לעיר הזאת.\p"
    .string "שמעתי שגם מר פוג'י לא במקור\n"
    .string "מהאזור הזה.$"

LavenderTown_VolunteerPokemonHouse_Text_WhereDidMrFujiGo::
    .string "זה מוזר, מר פוג'י לא כאן.\n"
    .string "לאן הוא הלך?$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiWasPrayingForCubonesMother::
    .string "מר פוג'י התפלל לבד\n"
    .string "עבור אמא של קיובון.$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiLooksAfterOrphanedMons::
    .string "זה באמת הבית של מר פוג'י.\p"
    .string "הוא ממש נחמד.\p"
    .string "הוא דואג לפוקימונים נטושים\n"
    .string "ויתומים.$"

LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug::
    .string "זה כל כך חמים!\n"
    .string "פוקימונים כל כך כיף לחבק.$"

LavenderTown_VolunteerPokemonHouse_Text_Nidorino::
    .string "נידורינו: גאוו!$"

LavenderTown_VolunteerPokemonHouse_Text_Psyduck::
    .string "פסיידאק: גואפה!$"

LavenderTown_VolunteerPokemonHouse_Text_IdLikeYouToHaveThis::
    .string "מר פוג'י: {PLAYER}…\p"
    .string "המשימה שלך להשלמת הפוקידקס\n"
    .string "דורשת מסירות חזקה.\p"
    .string "ללא אהבה עמוקה לפוקימונים,\n"
    .string "המשימה שלך עלולה להיכשל.\p"
    .string "אני לא בטוח אם זה יעזור לך,\n"
    .string "אבל אני רוצה שתיקח את זה.$"

LavenderTown_VolunteerPokemonHouse_Text_ReceivedPokeFluteFromMrFuji::
    .string "{PLAYER} קיבל את חליל הפוקימון\n"
    .string "ממר פוג'י.$"

LavenderTown_VolunteerPokemonHouse_Text_ExplainPokeFlute::
    .string "כשתשמע את חליל הפוקימון,\n"
    .string "פוקימונים ישנים יתעוררו מיד.\p"
    .string "נסה להשתמש בו על פוקימונים\n"
    .string "שמהווים מכשולים ישנים.$"

LavenderTown_VolunteerPokemonHouse_Text_MustMakeRoomForThis::
    .string "עליך לפנות מקום בשביל זה!$"

LavenderTown_VolunteerPokemonHouse_Text_HasPokeFluteHelpedYou::
    .string "מר פוג'י: האם חליל הפוקימון\n"
    .string "עזר לך?$"

LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped::
    .string "מגזין אוהדי פוקימון\n"
    .string "הגרלת הפרס החודשי!\p"
    .string "טופס ההשתתפות…\p"
    .string "נעלם! כנראה מישהו כבר הגיש.$"

LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf::
    .string "מגזיני פוקימון מסודרים על המדף.\p"
    .string "פוקימון אינסיידר…\p"
    .string "פוקימון פאן…$"
