PalletTown_Text_OakDontGoOut::
    .string "אוק: היי! חכה\n"
    .string "רגע! אל תלך!@$"
PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "אוק: זה מסוכן!\n"
    .string "פוקימונים פראים\l"
    .string "חיים בדשא!\p"
    .string "כדאי שיהיו לך\n"
    .string "פוקימונים משלך\l"
    .string "שיגנו עליך."
    .string "יש לי רעיון!\n"
    .string "בוא איתי!$"
PalletTown_Text_RaisingMonsToo::
    .string "גם אני מאמנת\n"
    .string "פוקימונים!\p"
    .string "כשהם יגדלו ויהיו\n"
    .string "חזקים, הם יגנו\l"
    .string "עלי!$"
PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "אפשר לאחסן\n"
    .string "דיגיטלית פריטים\l"
    .string "ואפילו פוקימונים,\l"
    .string "דרך מחשב!\p"
    .string "ממש פלאי\n"
    .string "הטכנולוגיה!$"
PalletTown_Text_OakPokemonResearchLab::
    .string "מעבדת הפוקימון\n"
    .string "של פרופ' אוק$"
PalletTown_Text_TownSign::
    .string "העיירה פאלט\n"
    .string "המסע הססגוני\l"
    .string "שלך עומד להתחיל!$"
PalletTown_Text_PlayersHouse::
    .string "הבית של {PLAYER}$"
PalletTown_Text_RivalsHouse::
    .string "הבית של {RIVAL}$"