PalletTown_Text_OakDontGoOut::
    .string "EJW: INN! LOI\n"
    .string "XGT! EP ZPe!@$"
PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "EJW: KI QSJOa!\n"
    .string "UJWNQJRNb UXENb\l"
    .string "LNNb FHYE!\p"
    .string "OHEN YNINJ Pe\n"
    .string "UJWNQJRNb QYPe\l"
    .string "YNGRJ TPNe."
    .string "NY PN XTNJa!\n"
    .string "FJE ENZN!$"
PalletTown_Text_RaisingMonsToo::
    .string "Gb ERN QEQRZ\n"
    .string "UJWNQJRNb!\p"
    .string "OYIb NGHPJ JNINJ\n"
    .string "LKWNb, Ib NGRJ\l"
    .string "TPN!$"
PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "EUYX PELSa\n"
    .string "HNGNMPNZ UXNMNb\l"
    .string "JEUNPJ UJWNQJRNb,\l"
    .string "HXe QLYF!\p"
    .string "QQY UPEN\n"
    .string "IMORJPJGNI!$"
PalletTown_Text_OakPokemonResearchLab::
    .string "QTFHZ IUJWNQJa\n"
    .string "YP UXJU' EJW$"
PalletTown_Text_TownSign::
    .string "ITNNXI UEPM\n"
    .string "IQST ISSGJRN\l"
    .string "YPe TJQH PIZLNP!$"
PalletTown_Text_PlayersHouse::
    .string "IFNZ YP {PLAYER}$"
PalletTown_Text_RivalsHouse::
    .string "IFNZ YP {RIVAL}$"