PokemonTower_5F_Text_RestHereInPurifiedSpace::
    .string "בוא, ילד!\n"
    .string "טיהרתי את המקום הזה.\l"
    .string "אתה יכול לנוח כאן.$"

PokemonTower_5F_Text_TammyIntro::
    .string "תן...לי...\n"
    .string "את...כל...$"

PokemonTower_5F_Text_TammyDefeat::
    .string "האהה!$"

PokemonTower_5F_Text_TammyPostBattle::
    .string "הייתי תחת השפעה.$"

PokemonTower_5F_Text_RuthIntro::
    .string "אתה...תצטרף...\n"
    .string "אלינו...$"

PokemonTower_5F_Text_RuthDefeat::
    .string "איזה סיוט!$"

PokemonTower_5F_Text_RuthPostBattle::
    .string "הייתי אחוזת דיבוק.$"

PokemonTower_5F_Text_KarinaIntro::
    .string "זומבים!$"

PokemonTower_5F_Text_KarinaDefeat::
    .string "הא?$"

PokemonTower_5F_Text_KarinaPostBattle::
    .string "חזרתי להכרה.$"

PokemonTower_5F_Text_JanaeIntro::
    .string "ארגה...\n"
    .string "ארף...$"

PokemonTower_5F_Text_JanaeDefeat::
    .string "וואה!$"

PokemonTower_5F_Text_JanaePostBattle::
    .string "נפלתי לידי רוחות רעות למרות\n"
    .string "האימונים שלי בהרים...$"

PokemonTower_5F_Text_PurifiedZoneMonsFullyHealed::
    .string "נכנסת לאזור המטוהר והמוגן.\p"
    .string "הפוקימונים של {PLAYER} נרפאו\n"
    .string "במלואם.$"
