Route16_NorthEntrance_1F_Text_NoPedestriansOnCyclingRoad::
    .string "אין כניסה להולכי רגל\n"
    .string "לדרך האופניים!$"

Route16_NorthEntrance_1F_Text_CyclingRoadIsDownhillCourse::
    .string "דרך האופניים היא מסלול בירידה\n"
    .string "ליד הים. זהו רכיבה מהנה.$"

Route16_NorthEntrance_1F_Text_ExcuseMeWaitUp::
    .string "סלח/י לי!\n"
    .string "חכה/י רגע, בבקשה!$"

Route16_NorthEntrance_1F_Text_HowdYouGetInGoodEffort::
    .string "איך הצלחת להיכנס?\n"
    .string "מאמץ יפה!$"
