LavenderTown_House2_Text_WantMeToRateNicknames::
    .string "שלום, שלום!\n"
    .string "אני הבוחן הרשמי של שמות!\p"
    .string "רוצה שאדרג את הכינויים של\n"
    .string "הפוקימונים שלך?$"

LavenderTown_House2_Text_CritiqueWhichMonsNickname::
    .string "את כינויו של איזה פוקימון\n"
    .string "תרצה שאבחן?$"

LavenderTown_House2_Text_GiveItANicerName::
    .string "{STR_VAR_1}, נכון?\n"
    .string "זה כינוי לא רע!\p"
    .string "אבל, תרצה שאעניק לו כינוי\n"
    .string "נחמד יותר?\p"
    .string "מה דעתך?$"

LavenderTown_House2_Text_WhatShallNewNicknameBe::
    .string "מעולה. אז, מה יהיה הכינוי\n"
    .string "החדש?$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsName::
    .string "סיימתי! מהיום הפוקימון הזה\n"
    .string "יוכר בשם {STR_VAR_1}!\p"
    .string "זה שם טוב יותר מהקודם!\n"
    .string "איזה מזל יש לך!$"

LavenderTown_House2_Text_ISeeComeVisitAgain::
    .string "אני מבין.\n"
    .string "חזור לבקר שוב.$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsSameName::
    .string "סיימתי! מהיום הפוקימון הזה\n"
    .string "יוכר בשם {STR_VAR_1}!\p"
    .string "זה נראה אותו הדבר, אבל\n"
    .string "למעשה, זה הרבה יותר טוב!\p"
    .string "איזה מזל יש לך!$"

LavenderTown_House2_Text_TrulyImpeccableName::
    .string "{STR_VAR_1}, נכון?\n"
    .string "זהו שם באמת ללא רבב!\p"
    .string "שמור היטב על {STR_VAR_1}!$"

LavenderTown_House2_Text_ThatIsMerelyAnEgg::
    .string "נו, נו.\n"
    .string "זה בסך הכול ביצה!$"
