RocketHideout_B3F_Text_Grunt1Intro::
    .string "הפסיק להתערב בעניינים של צוות\n"
    .string "רוקט או שתצטער!$"

RocketHideout_B3F_Text_Grunt1Defeat::
    .string "אוף!\n"
    .string "הובסתי!$"

RocketHideout_B3F_Text_Grunt1PostBattle::
    .string "משקפת סילף?\n"
    .string "אה, המכונה שהבוס גנב.\p"
    .string "היא נמצאת כאן איפשהו.$"

RocketHideout_B3F_Text_Grunt2Intro::
    .string "קיבלנו הודעה מלמעלה\n"
    .string "שאתה מגיע!$"

RocketHideout_B3F_Text_Grunt2Defeat::
    .string "מה?\n"
    .string "הפסדתי? לא!$"

RocketHideout_B3F_Text_Grunt2PostBattle::
    .string "לך קדימה!\p"
    .string "אבל אתה לא יכול להפעיל את המעלית\n"
    .string "בלי מפתח המעלית.$"
