SaffronCity_PokemonCenter_1F_Text_GrowthRatesDifferBySpecies::
    .string "קצב הגדילה של פוקימונים שונה\n"
    .string "ממין לממין.$"

SaffronCity_PokemonCenter_1F_Text_SilphCoVictimOfFame::
    .string "סילפ קו. ידועה לכולם.\p"
    .string "היא קורבן של התהילה שלה - היא\n"
    .string "משכה את צוות רוקט.$"

SaffronCity_PokemonCenter_1F_Text_GreatIfEliteFourCameBeatRockets::
    .string "הו…\n"
    .string "לא יהיה זה נהדר?\p"
    .string "אם רבעיית העלית תבוא ותשמיד\n"
    .string "את צוות רוקט?$"

SaffronCity_PokemonCenter_1F_Text_TeamRocketTookOff::
    .string "צוות רוקט עף!\n"
    .string "אנחנו יכולים לצאת בביטחון שוב!\l"
    .string "זה נהדר!$"
