FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
    .string "נתנו לפקח את\n"
    .string "הכינוי סלופוק.\p"
    .string "גם לו וגם לסלופוק יש הבעה ריקנית!$"

FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
    .string "סלופוק מאד משכיל\n"
    .string "בנושאי פוקימון!\p"
    .string "אפילו יש לו כמה מאובנים של\l"
    .string "פוקימונים נדירים שנכחדו!$"

FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
    .string "סלופוק נכנס, אבל\n"
    .string "לא הצלחתי להבין אותו.\p"
    .string "אני חושב שיש לו ליקוי בדיבור!$"

FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone::
    .string "הפקח סלופוק אמר שאם מישהו מגיע\n"
    .string "לפינה הכי רחוקה של איזור הספארי\p"
    .string "הוא יקבל פרס שווה!$"

