CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore::
    .string "שלום! ברוך הבא\n"
    .string "לחנות הגדולה של סלדון.\p"
    .string "תוכל למצוא את מפת החנות על השלט\l"
    .string "מימין.$"

CeladonCity_DepartmentStore_1F_Text_FloorDescriptions::
    .string "ק1: דלפק שירות\p"
    .string "ק2: הכל למאמן\p"
    .string "ק3: חנות משחקי מחשב\p"
    .string "ק4: חנות מזכרות\p"
    .string "ק5: בית מרקחת\p"
    .string "קומת גג: מכונות ממכר$"

CeladonCity_DepartmentStore_1F_Text_ServiceCounter::
    .string "ק1: דלפק שירות$"
	