PewterCity_House1_Text_Nidoran::
    .string "נידורן♂: בו-בו!$"

PewterCity_House1_Text_NidoranSit::
    .string "נידורן, שב!$"

PewterCity_House1_Text_TradeMonsAreFinicky::
    .string "הפוקימון שלנו הוא זר, ולכן הוא\n"
    .string "בררן וקשה לשליטה.\p"
    .string "פוקימון זר הוא פוקימון שקיבלת\n"
    .string "בסחר.\p"
    .string "הוא גדל מהר, אך עלול להתעלם\n"
    .string "ממאמן חסר ניסיון בקרב.\p"
    .string "אם רק היו לנו כמה תגים…$"
