VermilionCity_PokemonCenter_1F_Text_TrainerMonsStrongerThanWild::
    .string "גם אם הם באותו רמה,\n"
    .string "לפוקימונים יכולים להיות\l"
    .string "יכולות וסטטיסטיקות שונות.\p"
    .string "פוקימון שאומן על ידי מאמן חזק\n"
    .string "יותר מפוקימון פראי.$"

VermilionCity_PokemonCenter_1F_Text_PoisonedMonFaintedWhileWalking::
    .string "הפוקימון שלי היה מורעל!\n"
    .string "הוא התעלף בזמן שהלכנו!$"

VermilionCity_PokemonCenter_1F_Text_AllMonWeakToSpecificTypes::
    .string "נכון שפוקימון ברמה גבוהה\n"
    .string "יהיה חזק יותר…\p"
    .string "אבל, לכל פוקימון יש נקודות\n"
    .string "חולשה לסוגים מסוימים.\p"
    .string "נראה שאין פוקימון חזק באופן\n"
    .string "אוניברסלי.$"

VermilionCity_PokemonCenter_1F_Text_UrgeToBattleSomeoneAgain::
    .string "הדחף להילחם שוב עם מישהו\n"
    .string "שכבר נאבקת איתו…\p"
    .string "האם אי פעם היה לך את הדחף הזה?\n"
    .string "אני בטוח שכן.\p"
    .string "רציתי להילחם שוב ושוב עם\n"
    .string "אנשים מסוימים גם אני.\p"
    .string "לכן, אני מחלק את זה.\n"
    .string "בבקשה, קח אחד!$"

VermilionCity_PokemonCenter_1F_Text_UseDeviceForRematches::
    .string "תשתמש במכשיר הזה ותמצא\n"
    .string "מאמנים שמחפשים קרב חוזר.\p"
    .string "אתה חייב לטעון את הסוללה כדי\n"
    .string "להשתמש בו.$"

VermilionCity_PokemonCenter_1F_Text_ExplainVSSeeker::
    .string "איך משתמשים במאתר הקרבות?\n"
    .string "אין פה כלום מסובך.\p"
    .string "תשתמש בו ב-'ביפ-ביפ-ביפ', ואז\n"
    .string "המאמנים סביבך ישימו לב.\p"
    .string "אם מאמן כלשהו רוצה קרב חוזר,\n"
    .string "הוא יודיע לך מיד.\p"
    .string "טען את הסוללה שלו והשתמש\n"
    .string "בו כשאתה על הדרך.$"
