ViridianCity_Mart_Text_SayHiToOakForMe::
    .string "אוקי! מסור דרישת\n"
    .string "שלום לפרופ' אוק ממני!$"

ViridianCity_Mart_Text_YouCameFromPallet::
    .string "הי! הגעת לכאן\n"
    .string "מהעיירה פאלט?$"

ViridianCity_Mart_Text_TakeThisToProfOak::
    .string "אתה מכיר את פרופ'\n"
    .string "אוק, נכון?\p"
    .string "ההזמנה שלו הגיעה. אתה יכול למסור\l"
    .string "לו אותה?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk::
    .string "{PLAYER} קיבל את\n"
    .string "החבילה של אוק!{}$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
    .string "החנות הזאת מוכרת\n"
    .string "הרבה נוגדנים.$"

ViridianCity_Mart_Text_GotToBuySomePotions::
    .string "אוף! נגמרו השיקוים\n"
    .string "במלאי.$"