ViridianCity_House_Text_NicknamingIsFun::
    .string "להמציא כינויים\n"
    .string "זה כיף, אבל לא פשוט.\p"
    .string "הכי קל לזכור שמות רגילים.$"

ViridianCity_House_Text_MyDaddyLovesMonsToo::
    .string "אבא שלי\n"
    .string "אוהב פוקימונים.$"

ViridianCity_House_Text_Speary::
    .string "כידי: טטוויט!$"

ViridianCity_House_Text_SpearowNameSpeary::
    .string "ספירו\n"
    .string "כינוי: כידי$"