PalletTown_Text_OakDontGoOut::
    .string "אוק: היי! חכה רגע!\n"
    .string "אל תלך לשם!$"

PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "אוק: זה מסוכן! פוקימונים פראים\l"
    .string "חיים בדשא!\p"
    .string "כדאי שיהיו לך פוקימונים משלך\l"
    .string "שיגנו עליך.\p"
    .string "יש לי רעיון!\n"
    .string "בוא איתי!$"

PalletTown_Text_RaisingMonsToo::
    .string "גם אני מאמנת פוקימונים!\p"
    .string "כשהם יגדלו ויהיו\n"
    .string "חזקים, הם יגנו עלי!$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "אפשר לאחסן דיגיטלית פריטים\n"
    .string "ואפילו פוקימונים, דרך מחשב!\p"
    .string "ממש פלאי הטכנולוגיה!$"

PalletTown_Text_OakPokemonResearchLab::
    .string "מעבדת הפוקימון של פרופ' אוק$"

PalletTown_Text_PlayersHouse::
    .string "הבית של {PLAYER}$"

PalletTown_Text_RivalsHouse::
    .string "הבית של {RIVAL}$"

PalletTown_Text_TownSign::
    .string "העיירה פאלט\n"
    .string "המסע שלך מתחיל כאן!$"

PalletTown_Text_OakLetMeSeePokedex::
    .string "אוק: {PLAYER}!\n"
    .string "סוף סוף חזרת?\p"
    .string "נו, כמה כבר מילאת את\n"
    .string "ה-פוקידקס שלך?\p"
    .string "אני יכול לראות אותו?\p"
    .string "בוא נראה…$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .string "תפסת {STR_VAR_2}…\p"
    .string "הממ, נראה שאתה משקיע מאמץ רב.\p"
    .string "כשתצליח למלא אותו קצת יותר,\n"
    .string "תבוא להראות לי בבקשה.$"

PalletTown_Text_CaughtXImpressiveFollowMe::
    .string "תפסת… {STR_VAR_2}!?\n"
    .string "וואו זה מרשים ביותר!\p"
    .string "יש משהו שרציתי לבקש ממך\n"
    .string "{PLAYER}.\p"
    .string "בוא אחרי.$"

PalletTown_Text_OakYouEnjoyingTraveling::
    .string "אוק: {PLAYER}!\n"
    .string "נראה שאתה נהנה מהמסע שלך.\p"
    .string "כמו שאני מכיר אותך, אני יכול\n"
    .string "לדמיין אותך הולך אפילו למקומות\l"
    .string "יותר מיוחדים.\p"
    .string "תמשיך ככה!\n"
	.string "אין ספק שאתה חי את החיים.$"

