CeladonCity_Hotel_Text_ThisHotelIsForPeople::
    .string "פוקימונים? לא,\n"
    .string "כאן זה מלון של אנשים.\p"
    .string "אנחנו בתפוסה מלאה.$"

CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend::
    .string "אני בחופשה עם\n"
    .string "אחי ועם החבר שלי.\p"
    .string "העיר סלדון כל כך יפה!$"

CeladonCity_Hotel_Text_WhyDidSheBringBrother::
    .string "למה היא הביאה\n"
    .string "את אחיה?$"

CeladonCity_Hotel_Text_SisBroughtMeOnVacation::
    .string "ויפיי! אני בחופשה!\n"
    .string "אחותי הסכימה לי להצטרף! איזה כיף!$"
